#ifndef PLEX_MM_COMMON_FILEPATHS_H
#define PLEX_MM_COMMON_FILEPATHS_H

#include "meta/language.h"

// GRAPHICS ------------------------------------------------------------

// SPRITE THEATER

#define MMS_FILEPATH_TEX_SELECTIONFONT PLEX_RECDIRECTORY "common/graphics/spritetheater/selectionfont.png"
#define MMS_FILEPATH_TEX_STAGELABEL PLEX_RECDIRECTORY "common/graphics/spritetheater/stagelabel.png"
#define MMS_FILEPATH_TEX_BUBBLE PLEX_RECDIRECTORY "common/graphics/spritetheater/bubble.png"
#define MMS_FILEPATH_TEX_ARROW PLEX_RECDIRECTORY "common/graphics/spritetheater/arrow.png"

// SPRITES

// PAMALEANA

#define MMS_FILEPATH_TEX_PAMALEANASPRITEPLATE PLEX_RECDIRECTORY "common/graphics/sprites/pamaleana/pamaleanaSpritesplate.png"

// EXTRAPLOCAN

#define MMS_FILEPATH_TEX_EXTRAPLOCANSPRITEPLATE PLEX_RECDIRECTORY "common/graphics/sprites/extraplocan/extraplocanSpritesplate.png"

// MR. VENARIUS

#define MMS_FILEPATH_TEX_MRVENARIUS PLEX_RECDIRECTORY "common/graphics/sprites/mrvenarius/mrvenariusSpritesplate.png"

// LEVINE

#define MMS_FILEPATH_TEX_LEVINESPRITEPLATE PLEX_RECDIRECTORY "common/graphics/sprites/levine/levineSpritesplate.png"

// SPRITE THEATER BACKDROPS

#define MMS_FILEPATH_TEX_OFFICEBACK PLEX_RECDIRECTORY "common/graphics/backdrops/pampamsoffice.png"

// SOUND -----------------------------------------------------------------------------------------------------------------------------------------------

// SOUND EFFECTS

#define MM_COMMON_SOUNDPATH_KNOCKING PLEX_RECDIRECTORY "common/sound/soundeffects/knocking.wav"
#define MM_COMMON_SOUNDPATH_SHOCKCUE PLEX_RECDIRECTORY "common/sound/soundeffects/shockcue.wav"
#define MM_COMMON_SOUNDPATH_SURREALHONKHONK PLEX_RECDIRECTORY "common/sound/soundeffects/surrealhorn.wav"
#define MM_COMMON_SOUNDPATH_PAMENGINEREV PLEX_RECDIRECTORY "common/sound/soundeffects/pamenginerev.wav"
#define MM_COMMON_SOUNDPATH_PAMENGINERUN PLEX_RECDIRECTORY "common/sound/soundeffects/pamenginerun.wav"
#define MM_COMMON_SOUNDPATH_PAMENGINESTRUGGLE PLEX_RECDIRECTORY "common/sound/soundeffects/pamenginestruggle.wav"
#define MM_COMMON_SOUNDPATH_CRASH PLEX_RECDIRECTORY "common/sound/soundeffects/crash.wav"
#define MM_COMMON_SOUNDPATH_SURREALGLASSCRACK PLEX_RECDIRECTORY "common/sound/soundeffects/surrealglasscrack.wav"
#define MM_COMMON_SOUNDPATH_ZOOMBY PLEX_RECDIRECTORY "common/sound/soundeffects/zoomby.wav"
#define MM_COMMON_SOUNDPATH_TABLESCREECH PLEX_RECDIRECTORY "common/sound/soundeffects/screech.wav"
#define MM_COMMON_SOUNDPATH_CLUB PLEX_RECDIRECTORY "common/sound/soundeffects/club.wav"
#define MM_COMMON_SOUNDPATH_GROAN PLEX_RECDIRECTORY "common/sound/soundeffects/groan.wav"
#define MM_COMMON_SOUNDPATH_QUICKGROAN PLEX_RECDIRECTORY "common/sound/soundeffects/quickgroan.wav"
#define MM_COMMON_SOUNDPATH_SHOT PLEX_RECDIRECTORY "common/sound/soundeffects/shot.wav"
#define MM_COMMON_SOUNDPATH_EMPTYCHAMBER PLEX_RECDIRECTORY "common/sound/soundeffects/emptychamber.wav"
#define MM_COMMON_SOUNDPATH_RELOAD PLEX_RECDIRECTORY "common/sound/soundeffects/reload.wav"
#define MM_COMMON_SOUNDPATH_GULP PLEX_RECDIRECTORY "common/sound/soundeffects/gulp.wav"
#define MM_COMMON_SOUNDPATH_SMALLSHOT PLEX_RECDIRECTORY "common/sound/soundeffects/smallshot.wav"
#define MM_COMMON_SOUNDPATH_RAPIDSHOT PLEX_RECDIRECTORY "common/sound/soundeffects/rapidshot.wav"
#define MM_COMMON_SOUNDPATH_SHOTMISS PLEX_RECDIRECTORY "common/sound/soundeffects/shotmiss.wav"
#define MM_COMMON_SOUNDPATH_COWBOYBIRTH PLEX_RECDIRECTORY "common/sound/soundeffects/cowboybirth.wav"
#define MM_COMMON_SOUNDPATH_SHOTGUNSHOT PLEX_RECDIRECTORY "common/sound/soundeffects/shotgunshot.wav"
#define MM_COMMON_SOUNDPATH_SLASH PLEX_RECDIRECTORY "common/sound/soundeffects/slash.wav"
#define MM_COMMON_SOUNDPATH_RAYGUN PLEX_RECDIRECTORY "common/sound/soundeffects/raygun.wav"
#define MM_COMMON_SOUNDPATH_EXPLOSION PLEX_RECDIRECTORY "common/sound/soundeffects/explosion.wav"
#define MM_COMMON_SOUNDPATH_CHAINSAWCUT PLEX_RECDIRECTORY "common/sound/soundeffects/chainsawcut.wav"
#define MM_COMMON_SOUNDPATH_ARROW PLEX_RECDIRECTORY "common/sound/soundeffects/arrow.wav"
#define MM_COMMON_SOUNDPATH_EXPLOSIONLOOP PLEX_RECDIRECTORY "common/sound/soundeffects/explosionloop.wav"
#define MM_COMMON_SOUNDPATH_DOORSLAM PLEX_RECDIRECTORY "common/sound/soundeffects/doorslam.wav"
#define MM_COMMON_SOUNDPATH_CRUELTWIST PLEX_RECDIRECTORY "common/sound/soundeffects/crueltwist.wav"
#define MM_COMMON_SOUNDPATH_ELECTRICSHOCK PLEX_RECDIRECTORY "common/sound/soundeffects/electricshock.wav"

// MAIN THEME

#define MM_COMMON_MUSICPATH_MAIN_LOOP PLEX_RECDIRECTORY "common/sound/themes/main/loop.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWA0 PLEX_RECDIRECTORY "common/sound/themes/main/rawA0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA1 PLEX_RECDIRECTORY "common/sound/themes/main/rawA1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA2 PLEX_RECDIRECTORY "common/sound/themes/main/rawA2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA3 PLEX_RECDIRECTORY "common/sound/themes/main/rawA3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA4 PLEX_RECDIRECTORY "common/sound/themes/main/rawA4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA5 PLEX_RECDIRECTORY "common/sound/themes/main/rawA5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA6 PLEX_RECDIRECTORY "common/sound/themes/main/rawA6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA7 PLEX_RECDIRECTORY "common/sound/themes/main/rawA7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA8 PLEX_RECDIRECTORY "common/sound/themes/main/rawA8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA9 PLEX_RECDIRECTORY "common/sound/themes/main/rawA9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA10 PLEX_RECDIRECTORY "common/sound/themes/main/rawA10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA11 PLEX_RECDIRECTORY "common/sound/themes/main/rawA11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA12 PLEX_RECDIRECTORY "common/sound/themes/main/rawA12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA13 PLEX_RECDIRECTORY "common/sound/themes/main/rawA13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA14 PLEX_RECDIRECTORY "common/sound/themes/main/rawA14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA15 PLEX_RECDIRECTORY "common/sound/themes/main/rawA15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA16 PLEX_RECDIRECTORY "common/sound/themes/main/rawA16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA17 PLEX_RECDIRECTORY "common/sound/themes/main/rawA17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA18 PLEX_RECDIRECTORY "common/sound/themes/main/rawA18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA19 PLEX_RECDIRECTORY "common/sound/themes/main/rawA19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA20 PLEX_RECDIRECTORY "common/sound/themes/main/rawA20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA21 PLEX_RECDIRECTORY "common/sound/themes/main/rawA21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA22 PLEX_RECDIRECTORY "common/sound/themes/main/rawA22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA23 PLEX_RECDIRECTORY "common/sound/themes/main/rawA23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA24 PLEX_RECDIRECTORY "common/sound/themes/main/rawA24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA25 PLEX_RECDIRECTORY "common/sound/themes/main/rawA25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA26 PLEX_RECDIRECTORY "common/sound/themes/main/rawA26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA27 PLEX_RECDIRECTORY "common/sound/themes/main/rawA27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA28 PLEX_RECDIRECTORY "common/sound/themes/main/rawA28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA29 PLEX_RECDIRECTORY "common/sound/themes/main/rawA29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA30 PLEX_RECDIRECTORY "common/sound/themes/main/rawA30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA31 PLEX_RECDIRECTORY "common/sound/themes/main/rawA31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA32 PLEX_RECDIRECTORY "common/sound/themes/main/rawA32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA33 PLEX_RECDIRECTORY "common/sound/themes/main/rawA33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA34 PLEX_RECDIRECTORY "common/sound/themes/main/rawA34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA35 PLEX_RECDIRECTORY "common/sound/themes/main/rawA35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA36 PLEX_RECDIRECTORY "common/sound/themes/main/rawA36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA37 PLEX_RECDIRECTORY "common/sound/themes/main/rawA37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA38 PLEX_RECDIRECTORY "common/sound/themes/main/rawA38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA39 PLEX_RECDIRECTORY "common/sound/themes/main/rawA39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA40 PLEX_RECDIRECTORY "common/sound/themes/main/rawA40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA41 PLEX_RECDIRECTORY "common/sound/themes/main/rawA41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA42 PLEX_RECDIRECTORY "common/sound/themes/main/rawA42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA43 PLEX_RECDIRECTORY "common/sound/themes/main/rawA43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA44 PLEX_RECDIRECTORY "common/sound/themes/main/rawA44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA45 PLEX_RECDIRECTORY "common/sound/themes/main/rawA45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA46 PLEX_RECDIRECTORY "common/sound/themes/main/rawA46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA47 PLEX_RECDIRECTORY "common/sound/themes/main/rawA47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA48 PLEX_RECDIRECTORY "common/sound/themes/main/rawA48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA49 PLEX_RECDIRECTORY "common/sound/themes/main/rawA49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWB0 PLEX_RECDIRECTORY "common/sound/themes/main/rawB0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB1 PLEX_RECDIRECTORY "common/sound/themes/main/rawB1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB2 PLEX_RECDIRECTORY "common/sound/themes/main/rawB2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB3 PLEX_RECDIRECTORY "common/sound/themes/main/rawB3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB4 PLEX_RECDIRECTORY "common/sound/themes/main/rawB4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB5 PLEX_RECDIRECTORY "common/sound/themes/main/rawB5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB6 PLEX_RECDIRECTORY "common/sound/themes/main/rawB6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB7 PLEX_RECDIRECTORY "common/sound/themes/main/rawB7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB8 PLEX_RECDIRECTORY "common/sound/themes/main/rawB8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB9 PLEX_RECDIRECTORY "common/sound/themes/main/rawB9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB10 PLEX_RECDIRECTORY "common/sound/themes/main/rawB10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB11 PLEX_RECDIRECTORY "common/sound/themes/main/rawB11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB12 PLEX_RECDIRECTORY "common/sound/themes/main/rawB12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB13 PLEX_RECDIRECTORY "common/sound/themes/main/rawB13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB14 PLEX_RECDIRECTORY "common/sound/themes/main/rawB14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB15 PLEX_RECDIRECTORY "common/sound/themes/main/rawB15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB16 PLEX_RECDIRECTORY "common/sound/themes/main/rawB16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB17 PLEX_RECDIRECTORY "common/sound/themes/main/rawB17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB18 PLEX_RECDIRECTORY "common/sound/themes/main/rawB18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB19 PLEX_RECDIRECTORY "common/sound/themes/main/rawB19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB20 PLEX_RECDIRECTORY "common/sound/themes/main/rawB20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB21 PLEX_RECDIRECTORY "common/sound/themes/main/rawB21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB22 PLEX_RECDIRECTORY "common/sound/themes/main/rawB22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB23 PLEX_RECDIRECTORY "common/sound/themes/main/rawB23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB24 PLEX_RECDIRECTORY "common/sound/themes/main/rawB24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB25 PLEX_RECDIRECTORY "common/sound/themes/main/rawB25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB26 PLEX_RECDIRECTORY "common/sound/themes/main/rawB26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB27 PLEX_RECDIRECTORY "common/sound/themes/main/rawB27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB28 PLEX_RECDIRECTORY "common/sound/themes/main/rawB28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB29 PLEX_RECDIRECTORY "common/sound/themes/main/rawB29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB30 PLEX_RECDIRECTORY "common/sound/themes/main/rawB30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB31 PLEX_RECDIRECTORY "common/sound/themes/main/rawB31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB32 PLEX_RECDIRECTORY "common/sound/themes/main/rawB32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB33 PLEX_RECDIRECTORY "common/sound/themes/main/rawB33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB34 PLEX_RECDIRECTORY "common/sound/themes/main/rawB34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB35 PLEX_RECDIRECTORY "common/sound/themes/main/rawB35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB36 PLEX_RECDIRECTORY "common/sound/themes/main/rawB36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB37 PLEX_RECDIRECTORY "common/sound/themes/main/rawB37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB38 PLEX_RECDIRECTORY "common/sound/themes/main/rawB38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB39 PLEX_RECDIRECTORY "common/sound/themes/main/rawB39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB40 PLEX_RECDIRECTORY "common/sound/themes/main/rawB40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB41 PLEX_RECDIRECTORY "common/sound/themes/main/rawB41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB42 PLEX_RECDIRECTORY "common/sound/themes/main/rawB42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB43 PLEX_RECDIRECTORY "common/sound/themes/main/rawB43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB44 PLEX_RECDIRECTORY "common/sound/themes/main/rawB44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB45 PLEX_RECDIRECTORY "common/sound/themes/main/rawB45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB46 PLEX_RECDIRECTORY "common/sound/themes/main/rawB46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB47 PLEX_RECDIRECTORY "common/sound/themes/main/rawB47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB48 PLEX_RECDIRECTORY "common/sound/themes/main/rawB48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB49 PLEX_RECDIRECTORY "common/sound/themes/main/rawB49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWC0 PLEX_RECDIRECTORY "common/sound/themes/main/rawC0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC1 PLEX_RECDIRECTORY "common/sound/themes/main/rawC1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC2 PLEX_RECDIRECTORY "common/sound/themes/main/rawC2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC3 PLEX_RECDIRECTORY "common/sound/themes/main/rawC3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC4 PLEX_RECDIRECTORY "common/sound/themes/main/rawC4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC5 PLEX_RECDIRECTORY "common/sound/themes/main/rawC5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC6 PLEX_RECDIRECTORY "common/sound/themes/main/rawC6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC7 PLEX_RECDIRECTORY "common/sound/themes/main/rawC7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC8 PLEX_RECDIRECTORY "common/sound/themes/main/rawC8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC9 PLEX_RECDIRECTORY "common/sound/themes/main/rawC9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC10 PLEX_RECDIRECTORY "common/sound/themes/main/rawC10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC11 PLEX_RECDIRECTORY "common/sound/themes/main/rawC11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC12 PLEX_RECDIRECTORY "common/sound/themes/main/rawC12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC13 PLEX_RECDIRECTORY "common/sound/themes/main/rawC13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC14 PLEX_RECDIRECTORY "common/sound/themes/main/rawC14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC15 PLEX_RECDIRECTORY "common/sound/themes/main/rawC15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC16 PLEX_RECDIRECTORY "common/sound/themes/main/rawC16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC17 PLEX_RECDIRECTORY "common/sound/themes/main/rawC17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC18 PLEX_RECDIRECTORY "common/sound/themes/main/rawC18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC19 PLEX_RECDIRECTORY "common/sound/themes/main/rawC19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC20 PLEX_RECDIRECTORY "common/sound/themes/main/rawC20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC21 PLEX_RECDIRECTORY "common/sound/themes/main/rawC21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC22 PLEX_RECDIRECTORY "common/sound/themes/main/rawC22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC23 PLEX_RECDIRECTORY "common/sound/themes/main/rawC23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC24 PLEX_RECDIRECTORY "common/sound/themes/main/rawC24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC25 PLEX_RECDIRECTORY "common/sound/themes/main/rawC25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC26 PLEX_RECDIRECTORY "common/sound/themes/main/rawC26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC27 PLEX_RECDIRECTORY "common/sound/themes/main/rawC27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC28 PLEX_RECDIRECTORY "common/sound/themes/main/rawC28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC29 PLEX_RECDIRECTORY "common/sound/themes/main/rawC29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC30 PLEX_RECDIRECTORY "common/sound/themes/main/rawC30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC31 PLEX_RECDIRECTORY "common/sound/themes/main/rawC31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC32 PLEX_RECDIRECTORY "common/sound/themes/main/rawC32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC33 PLEX_RECDIRECTORY "common/sound/themes/main/rawC33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC34 PLEX_RECDIRECTORY "common/sound/themes/main/rawC34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC35 PLEX_RECDIRECTORY "common/sound/themes/main/rawC35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC36 PLEX_RECDIRECTORY "common/sound/themes/main/rawC36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC37 PLEX_RECDIRECTORY "common/sound/themes/main/rawC37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC38 PLEX_RECDIRECTORY "common/sound/themes/main/rawC38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC39 PLEX_RECDIRECTORY "common/sound/themes/main/rawC39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC40 PLEX_RECDIRECTORY "common/sound/themes/main/rawC40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC41 PLEX_RECDIRECTORY "common/sound/themes/main/rawC41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC42 PLEX_RECDIRECTORY "common/sound/themes/main/rawC42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC43 PLEX_RECDIRECTORY "common/sound/themes/main/rawC43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC44 PLEX_RECDIRECTORY "common/sound/themes/main/rawC44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC45 PLEX_RECDIRECTORY "common/sound/themes/main/rawC45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC46 PLEX_RECDIRECTORY "common/sound/themes/main/rawC46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC47 PLEX_RECDIRECTORY "common/sound/themes/main/rawC47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC48 PLEX_RECDIRECTORY "common/sound/themes/main/rawC48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC49 PLEX_RECDIRECTORY "common/sound/themes/main/rawC49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWD0 PLEX_RECDIRECTORY "common/sound/themes/main/rawD0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD1 PLEX_RECDIRECTORY "common/sound/themes/main/rawD1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD2 PLEX_RECDIRECTORY "common/sound/themes/main/rawD2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD3 PLEX_RECDIRECTORY "common/sound/themes/main/rawD3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD4 PLEX_RECDIRECTORY "common/sound/themes/main/rawD4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD5 PLEX_RECDIRECTORY "common/sound/themes/main/rawD5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD6 PLEX_RECDIRECTORY "common/sound/themes/main/rawD6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD7 PLEX_RECDIRECTORY "common/sound/themes/main/rawD7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD8 PLEX_RECDIRECTORY "common/sound/themes/main/rawD8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD9 PLEX_RECDIRECTORY "common/sound/themes/main/rawD9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD10 PLEX_RECDIRECTORY "common/sound/themes/main/rawD10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD11 PLEX_RECDIRECTORY "common/sound/themes/main/rawD11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD12 PLEX_RECDIRECTORY "common/sound/themes/main/rawD12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD13 PLEX_RECDIRECTORY "common/sound/themes/main/rawD13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD14 PLEX_RECDIRECTORY "common/sound/themes/main/rawD14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD15 PLEX_RECDIRECTORY "common/sound/themes/main/rawD15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD16 PLEX_RECDIRECTORY "common/sound/themes/main/rawD16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD17 PLEX_RECDIRECTORY "common/sound/themes/main/rawD17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD18 PLEX_RECDIRECTORY "common/sound/themes/main/rawD18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD19 PLEX_RECDIRECTORY "common/sound/themes/main/rawD19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD20 PLEX_RECDIRECTORY "common/sound/themes/main/rawD20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD21 PLEX_RECDIRECTORY "common/sound/themes/main/rawD21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD22 PLEX_RECDIRECTORY "common/sound/themes/main/rawD22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD23 PLEX_RECDIRECTORY "common/sound/themes/main/rawD23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD24 PLEX_RECDIRECTORY "common/sound/themes/main/rawD24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD25 PLEX_RECDIRECTORY "common/sound/themes/main/rawD25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD26 PLEX_RECDIRECTORY "common/sound/themes/main/rawD26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD27 PLEX_RECDIRECTORY "common/sound/themes/main/rawD27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD28 PLEX_RECDIRECTORY "common/sound/themes/main/rawD28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD29 PLEX_RECDIRECTORY "common/sound/themes/main/rawD29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD30 PLEX_RECDIRECTORY "common/sound/themes/main/rawD30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD31 PLEX_RECDIRECTORY "common/sound/themes/main/rawD31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD32 PLEX_RECDIRECTORY "common/sound/themes/main/rawD32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD33 PLEX_RECDIRECTORY "common/sound/themes/main/rawD33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD34 PLEX_RECDIRECTORY "common/sound/themes/main/rawD34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD35 PLEX_RECDIRECTORY "common/sound/themes/main/rawD35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD36 PLEX_RECDIRECTORY "common/sound/themes/main/rawD36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD37 PLEX_RECDIRECTORY "common/sound/themes/main/rawD37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD38 PLEX_RECDIRECTORY "common/sound/themes/main/rawD38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD39 PLEX_RECDIRECTORY "common/sound/themes/main/rawD39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD40 PLEX_RECDIRECTORY "common/sound/themes/main/rawD40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD41 PLEX_RECDIRECTORY "common/sound/themes/main/rawD41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD42 PLEX_RECDIRECTORY "common/sound/themes/main/rawD42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD43 PLEX_RECDIRECTORY "common/sound/themes/main/rawD43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD44 PLEX_RECDIRECTORY "common/sound/themes/main/rawD44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD45 PLEX_RECDIRECTORY "common/sound/themes/main/rawD45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD46 PLEX_RECDIRECTORY "common/sound/themes/main/rawD46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD47 PLEX_RECDIRECTORY "common/sound/themes/main/rawD47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD48 PLEX_RECDIRECTORY "common/sound/themes/main/rawD48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD49 PLEX_RECDIRECTORY "common/sound/themes/main/rawD49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWE0 PLEX_RECDIRECTORY "common/sound/themes/main/rawE0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE1 PLEX_RECDIRECTORY "common/sound/themes/main/rawE1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE2 PLEX_RECDIRECTORY "common/sound/themes/main/rawE2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE3 PLEX_RECDIRECTORY "common/sound/themes/main/rawE3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE4 PLEX_RECDIRECTORY "common/sound/themes/main/rawE4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE5 PLEX_RECDIRECTORY "common/sound/themes/main/rawE5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE6 PLEX_RECDIRECTORY "common/sound/themes/main/rawE6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE7 PLEX_RECDIRECTORY "common/sound/themes/main/rawE7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE8 PLEX_RECDIRECTORY "common/sound/themes/main/rawE8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE9 PLEX_RECDIRECTORY "common/sound/themes/main/rawE9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE10 PLEX_RECDIRECTORY "common/sound/themes/main/rawE10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE11 PLEX_RECDIRECTORY "common/sound/themes/main/rawE11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE12 PLEX_RECDIRECTORY "common/sound/themes/main/rawE12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE13 PLEX_RECDIRECTORY "common/sound/themes/main/rawE13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE14 PLEX_RECDIRECTORY "common/sound/themes/main/rawE14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE15 PLEX_RECDIRECTORY "common/sound/themes/main/rawE15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE16 PLEX_RECDIRECTORY "common/sound/themes/main/rawE16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE17 PLEX_RECDIRECTORY "common/sound/themes/main/rawE17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE18 PLEX_RECDIRECTORY "common/sound/themes/main/rawE18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE19 PLEX_RECDIRECTORY "common/sound/themes/main/rawE19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE20 PLEX_RECDIRECTORY "common/sound/themes/main/rawE20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE21 PLEX_RECDIRECTORY "common/sound/themes/main/rawE21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE22 PLEX_RECDIRECTORY "common/sound/themes/main/rawE22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE23 PLEX_RECDIRECTORY "common/sound/themes/main/rawE23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE24 PLEX_RECDIRECTORY "common/sound/themes/main/rawE24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE25 PLEX_RECDIRECTORY "common/sound/themes/main/rawE25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE26 PLEX_RECDIRECTORY "common/sound/themes/main/rawE26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE27 PLEX_RECDIRECTORY "common/sound/themes/main/rawE27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE28 PLEX_RECDIRECTORY "common/sound/themes/main/rawE28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE29 PLEX_RECDIRECTORY "common/sound/themes/main/rawE29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE30 PLEX_RECDIRECTORY "common/sound/themes/main/rawE30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE31 PLEX_RECDIRECTORY "common/sound/themes/main/rawE31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE32 PLEX_RECDIRECTORY "common/sound/themes/main/rawE32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE33 PLEX_RECDIRECTORY "common/sound/themes/main/rawE33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE34 PLEX_RECDIRECTORY "common/sound/themes/main/rawE34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE35 PLEX_RECDIRECTORY "common/sound/themes/main/rawE35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE36 PLEX_RECDIRECTORY "common/sound/themes/main/rawE36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE37 PLEX_RECDIRECTORY "common/sound/themes/main/rawE37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE38 PLEX_RECDIRECTORY "common/sound/themes/main/rawE38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE39 PLEX_RECDIRECTORY "common/sound/themes/main/rawE39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE40 PLEX_RECDIRECTORY "common/sound/themes/main/rawE40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE41 PLEX_RECDIRECTORY "common/sound/themes/main/rawE41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE42 PLEX_RECDIRECTORY "common/sound/themes/main/rawE42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE43 PLEX_RECDIRECTORY "common/sound/themes/main/rawE43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE44 PLEX_RECDIRECTORY "common/sound/themes/main/rawE44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE45 PLEX_RECDIRECTORY "common/sound/themes/main/rawE45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE46 PLEX_RECDIRECTORY "common/sound/themes/main/rawE46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE47 PLEX_RECDIRECTORY "common/sound/themes/main/rawE47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE48 PLEX_RECDIRECTORY "common/sound/themes/main/rawE48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE49 PLEX_RECDIRECTORY "common/sound/themes/main/rawE49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWF0 PLEX_RECDIRECTORY "common/sound/themes/main/rawF0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF1 PLEX_RECDIRECTORY "common/sound/themes/main/rawF1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF2 PLEX_RECDIRECTORY "common/sound/themes/main/rawF2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF3 PLEX_RECDIRECTORY "common/sound/themes/main/rawF3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF4 PLEX_RECDIRECTORY "common/sound/themes/main/rawF4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF5 PLEX_RECDIRECTORY "common/sound/themes/main/rawF5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF6 PLEX_RECDIRECTORY "common/sound/themes/main/rawF6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF7 PLEX_RECDIRECTORY "common/sound/themes/main/rawF7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF8 PLEX_RECDIRECTORY "common/sound/themes/main/rawF8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF9 PLEX_RECDIRECTORY "common/sound/themes/main/rawF9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF10 PLEX_RECDIRECTORY "common/sound/themes/main/rawF10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF11 PLEX_RECDIRECTORY "common/sound/themes/main/rawF11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF12 PLEX_RECDIRECTORY "common/sound/themes/main/rawF12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF13 PLEX_RECDIRECTORY "common/sound/themes/main/rawF13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF14 PLEX_RECDIRECTORY "common/sound/themes/main/rawF14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF15 PLEX_RECDIRECTORY "common/sound/themes/main/rawF15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF16 PLEX_RECDIRECTORY "common/sound/themes/main/rawF16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF17 PLEX_RECDIRECTORY "common/sound/themes/main/rawF17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF18 PLEX_RECDIRECTORY "common/sound/themes/main/rawF18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF19 PLEX_RECDIRECTORY "common/sound/themes/main/rawF19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF20 PLEX_RECDIRECTORY "common/sound/themes/main/rawF20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF21 PLEX_RECDIRECTORY "common/sound/themes/main/rawF21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF22 PLEX_RECDIRECTORY "common/sound/themes/main/rawF22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF23 PLEX_RECDIRECTORY "common/sound/themes/main/rawF23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF24 PLEX_RECDIRECTORY "common/sound/themes/main/rawF24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF25 PLEX_RECDIRECTORY "common/sound/themes/main/rawF25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF26 PLEX_RECDIRECTORY "common/sound/themes/main/rawF26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF27 PLEX_RECDIRECTORY "common/sound/themes/main/rawF27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF28 PLEX_RECDIRECTORY "common/sound/themes/main/rawF28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF29 PLEX_RECDIRECTORY "common/sound/themes/main/rawF29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF30 PLEX_RECDIRECTORY "common/sound/themes/main/rawF30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF31 PLEX_RECDIRECTORY "common/sound/themes/main/rawF31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF32 PLEX_RECDIRECTORY "common/sound/themes/main/rawF32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF33 PLEX_RECDIRECTORY "common/sound/themes/main/rawF33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF34 PLEX_RECDIRECTORY "common/sound/themes/main/rawF34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF35 PLEX_RECDIRECTORY "common/sound/themes/main/rawF35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF36 PLEX_RECDIRECTORY "common/sound/themes/main/rawF36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF37 PLEX_RECDIRECTORY "common/sound/themes/main/rawF37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF38 PLEX_RECDIRECTORY "common/sound/themes/main/rawF38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF39 PLEX_RECDIRECTORY "common/sound/themes/main/rawF39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF40 PLEX_RECDIRECTORY "common/sound/themes/main/rawF40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF41 PLEX_RECDIRECTORY "common/sound/themes/main/rawF41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF42 PLEX_RECDIRECTORY "common/sound/themes/main/rawF42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF43 PLEX_RECDIRECTORY "common/sound/themes/main/rawF43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF44 PLEX_RECDIRECTORY "common/sound/themes/main/rawF44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF45 PLEX_RECDIRECTORY "common/sound/themes/main/rawF45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF46 PLEX_RECDIRECTORY "common/sound/themes/main/rawF46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF47 PLEX_RECDIRECTORY "common/sound/themes/main/rawF47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF48 PLEX_RECDIRECTORY "common/sound/themes/main/rawF48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF49 PLEX_RECDIRECTORY "common/sound/themes/main/rawF49.wav"

// EXTRAPLOCAN THEME

#define MM_COMMON_MUSICPATH_EXTRAP_INTROORCHA PLEX_RECDIRECTORY "common/sound/themes/extraplocan/introOrchA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_INTROORCHB PLEX_RECDIRECTORY "common/sound/themes/extraplocan/introOrchB.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_ORCHA PLEX_RECDIRECTORY "common/sound/themes/extraplocan/orchA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHB PLEX_RECDIRECTORY "common/sound/themes/extraplocan/orchB.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHC PLEX_RECDIRECTORY "common/sound/themes/extraplocan/orchC.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHD PLEX_RECDIRECTORY "common/sound/themes/extraplocan/orchD.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHE PLEX_RECDIRECTORY "common/sound/themes/extraplocan/orchE.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_INTROPERCA PLEX_RECDIRECTORY "common/sound/themes/extraplocan/introPercA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_INTROPERCB PLEX_RECDIRECTORY "common/sound/themes/extraplocan/introPercB.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_PERCA PLEX_RECDIRECTORY "common/sound/themes/extraplocan/percA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCB PLEX_RECDIRECTORY "common/sound/themes/extraplocan/percB.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCC PLEX_RECDIRECTORY "common/sound/themes/extraplocan/percC.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCD PLEX_RECDIRECTORY "common/sound/themes/extraplocan/percD.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCE PLEX_RECDIRECTORY "common/sound/themes/extraplocan/percE.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_VOXA PLEX_RECDIRECTORY "common/sound/themes/extraplocan/voxA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXB PLEX_RECDIRECTORY "common/sound/themes/extraplocan/voxB.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXC PLEX_RECDIRECTORY "common/sound/themes/extraplocan/voxC.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXD PLEX_RECDIRECTORY "common/sound/themes/extraplocan/voxD.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXE PLEX_RECDIRECTORY "common/sound/themes/extraplocan/voxE.wav"

// NEWSROOM

#define MM_COMMON_MUSICPATH_NEWSROOM_DRUM0 PLEX_RECDIRECTORY "common/sound/themes/newsroom/D0.wav"
#define MM_COMMON_MUSICPATH_NEWSROOM_DRUM1 PLEX_RECDIRECTORY "common/sound/themes/newsroom/D1.wav"

#define MM_COMMON_MUSICPATH_NEWSROOM_TRUMPET0 PLEX_RECDIRECTORY "common/sound/themes/newsroom/T0.wav"
#define MM_COMMON_MUSICPATH_NEWSROOM_TRUMPET1 PLEX_RECDIRECTORY "common/sound/themes/newsroom/T1.wav"

#define MM_COMMON_MUSICPATH_NEWSROOM_SYNTHA PLEX_RECDIRECTORY "common/sound/themes/newsroom/SA.wav"
#define MM_COMMON_MUSICPATH_NEWSROOM_SYNTHB PLEX_RECDIRECTORY "common/sound/themes/newsroom/SB.wav"

// COMEDY

#define MM_COMMON_MUSICPATH_COMEDY_BC0 PLEX_RECDIRECTORY "common/sound/themes/comedy/BC0.wav"
#define MM_COMMON_MUSICPATH_COMEDY_BC1 PLEX_RECDIRECTORY "common/sound/themes/comedy/BC1.wav"
#define MM_COMMON_MUSICPATH_COMEDY_BC2 PLEX_RECDIRECTORY "common/sound/themes/comedy/BC2.wav"
#define MM_COMMON_MUSICPATH_COMEDY_BC3 PLEX_RECDIRECTORY "common/sound/themes/comedy/BC3.wav"

#define MM_COMMON_MUSICPATH_COMEDY_D0 PLEX_RECDIRECTORY "common/sound/themes/comedy/D0.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D1 PLEX_RECDIRECTORY "common/sound/themes/comedy/D1.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D2 PLEX_RECDIRECTORY "common/sound/themes/comedy/D2.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D3 PLEX_RECDIRECTORY "common/sound/themes/comedy/D3.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D4A PLEX_RECDIRECTORY "common/sound/themes/comedy/D4A.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D4B PLEX_RECDIRECTORY "common/sound/themes/comedy/D4B.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D5 PLEX_RECDIRECTORY "common/sound/themes/comedy/D5.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D6A PLEX_RECDIRECTORY "common/sound/themes/comedy/D6A.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D6B PLEX_RECDIRECTORY "common/sound/themes/comedy/D6B.wav"

#define MM_COMMON_MUSICPATH_COMEDY_O0 PLEX_RECDIRECTORY "common/sound/themes/comedy/O0.wav"
#define MM_COMMON_MUSICPATH_COMEDY_O1 PLEX_RECDIRECTORY "common/sound/themes/comedy/O1.wav"
#define MM_COMMON_MUSICPATH_COMEDY_O3 PLEX_RECDIRECTORY "common/sound/themes/comedy/O3.wav"

// PANIC

#define MM_COMMON_MUSICPATH_PANIC_AMBIENCE PLEX_RECDIRECTORY "common/sound/themes/panic/ambience.wav"

#define MM_COMMON_MUSICPATH_PANIC_DRUMS PLEX_RECDIRECTORY "common/sound/themes/panic/drum.wav"

#define MM_COMMON_MUSICPATH_PANIC_PIANO PLEX_RECDIRECTORY "common/sound/themes/panic/piano.wav"

#define MM_COMMON_MUSICPATH_PANIC_TROMBONE PLEX_RECDIRECTORY "common/sound/themes/panic/trombone.wav"

#define MM_COMMON_MUSICPATH_PANIC_AMSYNTH0 PLEX_RECDIRECTORY "common/sound/themes/panic/amsynth0.wav"
#define MM_COMMON_MUSICPATH_PANIC_AMSYNTH1 PLEX_RECDIRECTORY "common/sound/themes/panic/amsynth1.wav"

#define MM_COMMON_MUSICPATH_PANIC_SAXREP0 PLEX_RECDIRECTORY "common/sound/themes/panic/saxrep0.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXREP1 PLEX_RECDIRECTORY "common/sound/themes/panic/saxrep1.wav"

#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO0 PLEX_RECDIRECTORY "common/sound/themes/panic/saxsolo0.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO1 PLEX_RECDIRECTORY "common/sound/themes/panic/saxsolo1.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO2 PLEX_RECDIRECTORY "common/sound/themes/panic/saxsolo2.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO3 PLEX_RECDIRECTORY "common/sound/themes/panic/saxsolo3.wav"

// DARK CITY

#define MM_COMMON_MUSICPATH_DARKCITY_A0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/A0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_A1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/A1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_B0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/B0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_B1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/B1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_C0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/C0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_C1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/C1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_D0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/D0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_D1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/D1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_E0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/E0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_E1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/E1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_F0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/F0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_F1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/F1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_G0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/G0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_G1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/G1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_H0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/H0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_H1 PLEX_RECDIRECTORY "common/sound/themes/darkcity/H1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_I0 PLEX_RECDIRECTORY "common/sound/themes/darkcity/I0.wav"

// SUSPENSE THEME

#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETD PLEX_RECDIRECTORY "common/sound/themes/suspense/clarinetd.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETE PLEX_RECDIRECTORY "common/sound/themes/suspense/clarinete.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETF PLEX_RECDIRECTORY "common/sound/themes/suspense/clarinetf.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETG PLEX_RECDIRECTORY "common/sound/themes/suspense/clarinetg.wav"

#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSA PLEX_RECDIRECTORY "common/sound/themes/suspense/percussa.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSB PLEX_RECDIRECTORY "common/sound/themes/suspense/percussb.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSC PLEX_RECDIRECTORY "common/sound/themes/suspense/percussc.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSD PLEX_RECDIRECTORY "common/sound/themes/suspense/percussd.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSE PLEX_RECDIRECTORY "common/sound/themes/suspense/percusse.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSF PLEX_RECDIRECTORY "common/sound/themes/suspense/percussf.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSG PLEX_RECDIRECTORY "common/sound/themes/suspense/percussg.wav"

#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINA PLEX_RECDIRECTORY "common/sound/themes/suspense/violina.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINB PLEX_RECDIRECTORY "common/sound/themes/suspense/violinb.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINC PLEX_RECDIRECTORY "common/sound/themes/suspense/violinc.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLIND PLEX_RECDIRECTORY "common/sound/themes/suspense/violind.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINE PLEX_RECDIRECTORY "common/sound/themes/suspense/violine.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINF PLEX_RECDIRECTORY "common/sound/themes/suspense/violinf.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLING PLEX_RECDIRECTORY "common/sound/themes/suspense/violing.wav"

#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOA PLEX_RECDIRECTORY "common/sound/themes/suspense/pianoa.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOC PLEX_RECDIRECTORY "common/sound/themes/suspense/pianoc.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOD PLEX_RECDIRECTORY "common/sound/themes/suspense/pianod.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOE PLEX_RECDIRECTORY "common/sound/themes/suspense/pianoe.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOF PLEX_RECDIRECTORY "common/sound/themes/suspense/pianof.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOG PLEX_RECDIRECTORY "common/sound/themes/suspense/pianog.wav"

// PAMALEANA THEME

#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOA PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOB PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOC PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOD PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOE PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOF PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOG PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P6.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOH PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOI PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOJ PLEX_RECDIRECTORY "common/sound/themes/pamaleana/P9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSA PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSB PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSC PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSD PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSE PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSF PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSH PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSI PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSJ PLEX_RECDIRECTORY "common/sound/themes/pamaleana/CB9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINA PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINB PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINC PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLIND PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINE PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINF PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINH PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINI PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINJ PLEX_RECDIRECTORY "common/sound/themes/pamaleana/V9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAA PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAB PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAC PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAD PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAE PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAF PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAH PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAI PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAJ PLEX_RECDIRECTORY "common/sound/themes/pamaleana/M9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEA PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEB PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEC PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLED PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEE PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEF PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEG PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W6.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEH PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEI PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_WAVETABLEJ PLEX_RECDIRECTORY "common/sound/themes/pamaleana/W9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHA PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHB PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHC PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHD PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHE PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHF PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHG PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM6.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHH PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHI PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_AMSYNTHJ PLEX_RECDIRECTORY "common/sound/themes/pamaleana/AM9.wav"

// DAYDAY THEME

#define MM_COMMON_MUSICPATH_DAYTODAY_DRUM0 PLEX_RECDIRECTORY "common/sound/themes/daytoday/drum0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_DRUM1 PLEX_RECDIRECTORY "common/sound/themes/daytoday/drum1.wav"

#define MM_COMMON_MUSICPATH_DAYTODAY_MONOSYNTH0 PLEX_RECDIRECTORY "common/sound/themes/daytoday/monosynth0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_MONOSYNTH1 PLEX_RECDIRECTORY "common/sound/themes/daytoday/monosynth1.wav"

#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANA0 PLEX_RECDIRECTORY "common/sound/themes/daytoday/organA0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANA1 PLEX_RECDIRECTORY "common/sound/themes/daytoday/organA1.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANA2 PLEX_RECDIRECTORY "common/sound/themes/daytoday/organA2.wav"

#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANB0 PLEX_RECDIRECTORY "common/sound/themes/daytoday/organB0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANB1 PLEX_RECDIRECTORY "common/sound/themes/daytoday/organB1.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANB2 PLEX_RECDIRECTORY "common/sound/themes/daytoday/organB2.wav"

// DREAM THEME

#define MM_COMMON_MUSICPATH_DREAM_HARPA PLEX_RECDIRECTORY "common/sound/themes/dream/harp0.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPB PLEX_RECDIRECTORY "common/sound/themes/dream/harp1.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPC PLEX_RECDIRECTORY "common/sound/themes/dream/harp2.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPD PLEX_RECDIRECTORY "common/sound/themes/dream/harp3.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPE PLEX_RECDIRECTORY "common/sound/themes/dream/harp4.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPF PLEX_RECDIRECTORY "common/sound/themes/dream/harp5.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPG PLEX_RECDIRECTORY "common/sound/themes/dream/harp6.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPH PLEX_RECDIRECTORY "common/sound/themes/dream/harp7.wav"

#define MM_COMMON_MUSICPATH_DREAM_LOOP PLEX_RECDIRECTORY "common/sound/themes/dream/dreamloop.wav"

// DESERT WINDS

#define MM_COMMON_MUSICPATH_DESERTWINDS_BELL0 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/bell0.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_BELL1 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/bell1.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_GUITAR PLEX_RECDIRECTORY "common/sound/themes/desertwinds/guitar.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_TRAINWHISTLE PLEX_RECDIRECTORY "common/sound/themes/desertwinds/trainwhistle.wav"

#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE00 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/chaingang.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE01 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/cracklingfire.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE02 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/distantchatter.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE03 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/distantchurch.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE04 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/distantdigging.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE05 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/gustofwind.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE06 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/hawkdive.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE07 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/manslastgasp.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE08 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/snakehiss.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE09 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/spurs.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE10 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/tumbleweed.wav"
#define MM_COMMON_MUSICPATH_DESERTWINDS_ATMOSPHERE11 PLEX_RECDIRECTORY "common/sound/themes/desertwinds/atmosphere/wheelsinsand.wav"

// DESERT TOWN

#define MM_COMMON_MUSICPATH_DESERTTOWN_HARPA PLEX_RECDIRECTORY "common/sound/themes/deserttown/harpA.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_HARPB PLEX_RECDIRECTORY "common/sound/themes/deserttown/harpB.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_HARPC PLEX_RECDIRECTORY "common/sound/themes/deserttown/harpC.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_HARPD PLEX_RECDIRECTORY "common/sound/themes/deserttown/harpD.wav"

#define MM_COMMON_MUSICPATH_DESERTTOWN_ORGANA PLEX_RECDIRECTORY "common/sound/themes/deserttown/organA.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_ORGANB PLEX_RECDIRECTORY "common/sound/themes/deserttown/organB.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_ORGANC PLEX_RECDIRECTORY "common/sound/themes/deserttown/organC.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_ORGAND PLEX_RECDIRECTORY "common/sound/themes/deserttown/organD.wav"

#define MM_COMMON_MUSICPATH_DESERTTOWN_PIANOA PLEX_RECDIRECTORY "common/sound/themes/deserttown/pianoA.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_PIANOB PLEX_RECDIRECTORY "common/sound/themes/deserttown/pianoB.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_PIANOC PLEX_RECDIRECTORY "common/sound/themes/deserttown/pianoC.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_PIANOD PLEX_RECDIRECTORY "common/sound/themes/deserttown/pianoD.wav"

#define MM_COMMON_MUSICPATH_DESERTTOWN_GUITARA PLEX_RECDIRECTORY "common/sound/themes/deserttown/guitarA.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_GUITARB PLEX_RECDIRECTORY "common/sound/themes/deserttown/guitarB.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_GUITARC PLEX_RECDIRECTORY "common/sound/themes/deserttown/guitarC.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_GUITARD PLEX_RECDIRECTORY "common/sound/themes/deserttown/guitarD.wav"

#define MM_COMMON_MUSICPATH_DESERTTOWN_HARMONICAA PLEX_RECDIRECTORY "common/sound/themes/deserttown/harmonicaA.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_HARMONICAB PLEX_RECDIRECTORY "common/sound/themes/deserttown/harmonicaB.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_HARMONICAC PLEX_RECDIRECTORY "common/sound/themes/deserttown/harmonicaC.wav"
#define MM_COMMON_MUSICPATH_DESERTTOWN_HARMONICAD PLEX_RECDIRECTORY "common/sound/themes/deserttown/harmonicaD.wav"

// AGGRESSION THEME

#define MM_COMMON_MUSICPATH_AGGRESSION_DRUMS PLEX_RECDIRECTORY "common/sound/themes/aggression/drums.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_ORGAN1 PLEX_RECDIRECTORY "common/sound/themes/aggression/organ1.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_ORGAN2 PLEX_RECDIRECTORY "common/sound/themes/aggression/organ2.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_CELLOHARPSI PLEX_RECDIRECTORY "common/sound/themes/aggression/celloharpsi.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH1 PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth1.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH2A PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth2A.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH2B PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth2B.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH2C PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth2C.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH2D PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth2D.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH2E PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth2E.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH2F PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth2F.wav"
#define MM_COMMON_MUSICPATH_AGGRESSION_AMSYNTH2G PLEX_RECDIRECTORY "common/sound/themes/aggression/amsynth2G.wav"

// WORKDAY THEME

#define MM_COMMON_MUSICPATH_WORKDAY_DRUMS PLEX_RECDIRECTORY "common/sound/themes/workday/drums.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_PIANOA PLEX_RECDIRECTORY "common/sound/themes/workday/pianoA.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_PIANOB PLEX_RECDIRECTORY "common/sound/themes/workday/pianoB.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_BASSOONA PLEX_RECDIRECTORY "common/sound/themes/workday/bassoonA.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_BASSOONB PLEX_RECDIRECTORY "common/sound/themes/workday/bassoonB.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_BASSOONC PLEX_RECDIRECTORY "common/sound/themes/workday/bassoonC.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_GLOCKANDXYLOA PLEX_RECDIRECTORY "common/sound/themes/workday/glockandxyloA.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_GLOCKANDXYLOB PLEX_RECDIRECTORY "common/sound/themes/workday/glockandxyloB.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_GLOCKANDXYLOC PLEX_RECDIRECTORY "common/sound/themes/workday/glockandxyloC.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_TUBASAXCELLOA PLEX_RECDIRECTORY "common/sound/themes/workday/tubasaxcelloA.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_TUBASAXCELLOB PLEX_RECDIRECTORY "common/sound/themes/workday/tubasaxcelloB.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_TUBASAXCELLOC PLEX_RECDIRECTORY "common/sound/themes/workday/tubasaxcelloC.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_OCARINAA PLEX_RECDIRECTORY "common/sound/themes/workday/ocarinaA.wav"
#define MM_COMMON_MUSICPATH_WORKDAY_OCARINAB PLEX_RECDIRECTORY "common/sound/themes/workday/ocarinaB.wav"

// FEAR THEME

#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHA PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthA.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHB PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthB.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHC PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthC.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHD PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthD.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHE PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthE.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHF PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthF.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHG PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthG.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHH PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthH.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHI PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthI.wav"
#define MM_COMMON_MUSICPATH_FEAR_AMSYNTHJ PLEX_RECDIRECTORY "common/sound/themes/fear/amsynthJ.wav"

#define MM_COMMON_MUSICPATH_FEAR_ORGANA PLEX_RECDIRECTORY "common/sound/themes/fear/organA.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANB PLEX_RECDIRECTORY "common/sound/themes/fear/organB.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANC PLEX_RECDIRECTORY "common/sound/themes/fear/organC.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGAND PLEX_RECDIRECTORY "common/sound/themes/fear/organD.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANE PLEX_RECDIRECTORY "common/sound/themes/fear/organE.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANF PLEX_RECDIRECTORY "common/sound/themes/fear/organF.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANG PLEX_RECDIRECTORY "common/sound/themes/fear/organG.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANH PLEX_RECDIRECTORY "common/sound/themes/fear/organH.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANI PLEX_RECDIRECTORY "common/sound/themes/fear/organI.wav"
#define MM_COMMON_MUSICPATH_FEAR_ORGANJ PLEX_RECDIRECTORY "common/sound/themes/fear/organJ.wav"

#define MM_COMMON_MUSICPATH_FEAR_HARPA PLEX_RECDIRECTORY "common/sound/themes/fear/harpA.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPB PLEX_RECDIRECTORY "common/sound/themes/fear/harpB.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPC PLEX_RECDIRECTORY "common/sound/themes/fear/harpC.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPD PLEX_RECDIRECTORY "common/sound/themes/fear/harpD.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPE PLEX_RECDIRECTORY "common/sound/themes/fear/harpE.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPF PLEX_RECDIRECTORY "common/sound/themes/fear/harpF.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPG PLEX_RECDIRECTORY "common/sound/themes/fear/harpG.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPH PLEX_RECDIRECTORY "common/sound/themes/fear/harpH.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPI PLEX_RECDIRECTORY "common/sound/themes/fear/harpI.wav"
#define MM_COMMON_MUSICPATH_FEAR_HARPJ PLEX_RECDIRECTORY "common/sound/themes/fear/harpJ.wav"

#define MM_COMMON_MUSICPATH_FEAR_VIOLINA PLEX_RECDIRECTORY "common/sound/themes/fear/violinA.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLINB PLEX_RECDIRECTORY "common/sound/themes/fear/violinB.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLINC PLEX_RECDIRECTORY "common/sound/themes/fear/violinC.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLIND PLEX_RECDIRECTORY "common/sound/themes/fear/violinD.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLINE PLEX_RECDIRECTORY "common/sound/themes/fear/violinE.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLINF PLEX_RECDIRECTORY "common/sound/themes/fear/violinF.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLING PLEX_RECDIRECTORY "common/sound/themes/fear/violinG.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLINH PLEX_RECDIRECTORY "common/sound/themes/fear/violinH.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLINI PLEX_RECDIRECTORY "common/sound/themes/fear/violinI.wav"
#define MM_COMMON_MUSICPATH_FEAR_VIOLINJ PLEX_RECDIRECTORY "common/sound/themes/fear/violinJ.wav"

// PUNK THEME

#define MM_COMMON_MUSICPATH_PUNK_GUITAR PLEX_RECDIRECTORY "common/sound/themes/punk/guitar.wav"
#define MM_COMMON_MUSICPATH_PUNK_BASS PLEX_RECDIRECTORY "common/sound/themes/punk/bass.wav"
#define MM_COMMON_MUSICPATH_PUNK_DRUMS PLEX_RECDIRECTORY "common/sound/themes/punk/drums.wav"

#define MM_COMMON_MUSICPATH_PUNK_VOXA PLEX_RECDIRECTORY "common/sound/themes/punk/voxA.wav"
#define MM_COMMON_MUSICPATH_PUNK_VOXB PLEX_RECDIRECTORY "common/sound/themes/punk/voxB.wav"
#define MM_COMMON_MUSICPATH_PUNK_VOXC PLEX_RECDIRECTORY "common/sound/themes/punk/voxC.wav"

// METAL THEME

#define MM_COMMON_MUSICPATH_METAL_GUITAR PLEX_RECDIRECTORY "common/sound/themes/metal/geetar.wav"
#define MM_COMMON_MUSICPATH_METAL_BASS PLEX_RECDIRECTORY "common/sound/themes/metal/bass.wav"
#define MM_COMMON_MUSICPATH_METAL_DRUMS PLEX_RECDIRECTORY "common/sound/themes/metal/drums.wav"

// STRIFE THEME

#define MM_COMMON_MUSICPATH_STRIFE_LEFT1A PLEX_RECDIRECTORY "common/sound/themes/strife/left1A.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT1B PLEX_RECDIRECTORY "common/sound/themes/strife/left1B.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT1C PLEX_RECDIRECTORY "common/sound/themes/strife/left1C.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT1D PLEX_RECDIRECTORY "common/sound/themes/strife/left1D.wav"

#define MM_COMMON_MUSICPATH_STRIFE_LEFT2A PLEX_RECDIRECTORY "common/sound/themes/strife/left2A.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT2B PLEX_RECDIRECTORY "common/sound/themes/strife/left2B.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT2C PLEX_RECDIRECTORY "common/sound/themes/strife/left2C.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT2D PLEX_RECDIRECTORY "common/sound/themes/strife/left2D.wav"

#define MM_COMMON_MUSICPATH_STRIFE_LEFT3A PLEX_RECDIRECTORY "common/sound/themes/strife/left3A.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT3B PLEX_RECDIRECTORY "common/sound/themes/strife/left3B.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT3C PLEX_RECDIRECTORY "common/sound/themes/strife/left3C.wav"
#define MM_COMMON_MUSICPATH_STRIFE_LEFT3D PLEX_RECDIRECTORY "common/sound/themes/strife/left3D.wav"

#define MM_COMMON_MUSICPATH_STRIFE_RIGHT PLEX_RECDIRECTORY "common/sound/themes/strife/right.wav"
#define MM_COMMON_MUSICPATH_STRIFE_OBOE PLEX_RECDIRECTORY "common/sound/themes/strife/oboe.wav"
#define MM_COMMON_MUSICPATH_STRIFE_FLUTE PLEX_RECDIRECTORY "common/sound/themes/strife/flute.wav"
#define MM_COMMON_MUSICPATH_STRIFE_BASSOON PLEX_RECDIRECTORY "common/sound/themes/strife/bassoon.wav"
#define MM_COMMON_MUSICPATH_STRIFE_VIOLINS PLEX_RECDIRECTORY "common/sound/themes/strife/violins.wav"

#endif
