#ifndef MMS2_META_H
#define MMS2_META_H

#include "plex.h"

#include "mmcommon.h"

/////////////////
// DRAW LAYERS //
/////////////////

// DRAW LAYERS - GUI

#define MMS2_DRAWLAYER_GUI 0

#define MMS2_DRAWLAYER_SHOTICON 0
#define MMS2_DRAWLAYER_SHOTICONBACK 1
#define MMS2_DRAWLAYER_GUNGUI 1

#define MMS2_DRAWLAYER_MENUBACK 100
#define MMS2_DRAWLAYER_MENUFRONT 1

#define MMS2_DRAWLAYER_BORDER 1

#define MMS2_DRAWLAYER_AREAGUI 1

// DRAW LAYERS - CALM AREA

#define MMS2_DRAWLAYER_NPC 1
#define MMS2_DRAWLAYER_JAILBARS 2
#define MMS2_DRAWLAYER_JAILEDNPC 3

#define MMS2_DRAWLAYER_MAYORMESSAGE 0
#define MMS2_DRAWLAYER_MAYORCLICKBOX 2
#define MMS2_DRAWLAYER_MAYORNPC 3

#define MMS2_DRAWLAYER_TOWNBACKDROP 500

// DRAW LAYERS - ENEMY

#define MMS2_DRAWLAYER_ENEMYLAYERBASE 200

// DRAW LAYERS - ROOM

#define MMS2_DRAWLAYER_BACKDROP 9999

// DRAW LAYERS - FINAL BOSS

#define MMS2_DRAWLAYER_FINALBOSSDROP 9
#define MMS2_DRAWLAYER_FINALBOSSEXPLOSION 0
#define MMS2_DRAWLAYER_FINALBOSSLEVINEFALLRIGHT 101
#define MMS2_DRAWLAYER_FINALBOSSLEVINEFALLLEFT 100
#define MMS2_DRAWLAYER_FINALBOSSLEVINEFLY 200

#define MMS2_DRAWLAYER_FINALBOSS 10

///////////
// OTHER //
///////////

// ALL

#define MMS2_SHOTDURATION 200

#define MMS2_GENERATORINDEXCOUNT 20

#define MMS2_AREANAMES2COUNT 57

// PLAYER

#define MMS2_GUNCOUNT 13

#define MMS2_GUNSCROLLUNIT 6

// ENEMY

#define MMS2_ENEMYCOUNT 100

#define MMS2_ROLLDURATION 500

#define MMS2_ENEMYGENCOUNT 10

// COVER

#define MMS2_COVERCOUNT 100

#define MMS2_COVERGENCOUNT 100

#define MMS2_AIPATTERNCOUNT 10

// TREASURE

#define MMS2_TREASURECOUNT 25

// ROOM

#define MMS2_POINTPATH0 1000
#define MMS2_POINTPATH1 2500
#define MMS2_POINTPATH2 10000
#define MMS2_POINTPATH3 20000

#define MMS2_ROOMMOVEDURATION 1000

#define MMS2_AREANAMES1COUNT 80

// FINAL BOSS

#define MMS2_FINALBOSSMOVETIMEMIN 500
#define MMS2_FINALBOSSMOVETIMEMAX 2500

#define MMS2_FINALBOSSMOVEVELOCITYMIN 20
#define MMS2_FINALBOSSMOVEVELOCITYMAX 100

#define MMS2_FINALBOSSMAXHEALTH 55

#define MMS2_FINALBOSSDAMAGEDURATION 500

#define MMS2_FINALBOSSSHOOTCOOLMIN 1000
#define MMS2_FINALBOSSSHOOTCOOLMAX 5000

#define MMS2_FINALBOSSMINSHOTDURATION 1000

#define MMS2_FINALBOSSDROPBOXCOUNT 10

#define MMS2_FINALBOSSDROPBOXDURATIONMIN 2000
#define MMS2_FINALBOSSDROPBOXDURATIONMAX 10000

#define MMS2_FINALBOSSDROPBOXCOVERMAX 9
#define MMS2_FINALBOSSDROPBOXCOVERMIN 2

#define MMS2_FINALBOSSINTROCUTDURATION 25000
#define MMS2_FINALBOSSOUTROCUTDURATION 40000

#define MMS2_FINALBOSSINTROCUTDURATIONNOSOUND 500
#define MMS2_FINALBOSSOUTROCUTDURATIONNOSOUND 2000

#endif
