#ifndef PLEX_MEMPROFILE_H
#define PLEX_MEMPROFILE_H

#include "meta/cinclude.h"

// NOTE: typically you just want to let the defaults handle all of this:

// MEMORY

#define PLEX_MEMLIMIT_MEM_PRELOAD_LOW 16
#define PLEX_MEMLIMIT_MEM_PRELOAD_MEDIUM 64
#define PLEX_MEMLIMIT_MEM_PRELOAD_HIGH 256
#define PLEX_MEMLIMIT_MEM_PRELOAD_VERYHIGH 1024

#define PLEX_MEMLIMIT_MEMREUSE_LOW 8
#define PLEX_MEMLIMIT_MEMREUSE_MEDIUM 16
#define PLEX_MEMLIMIT_MEMREUSE_HIGH 128
#define PLEX_MEMLIMIT_MEMREUSE_VERYHIGH 512

// DEFAULTS

#define PLEX_MEMLIMIT_DEFAULTS_LOW 16
#define PLEX_MEMLIMIT_DEFAULTS_MEDIUM 24
#define PLEX_MEMLIMIT_DEFAULTS_HIGH 64
#define PLEX_MEMLIMIT_DEFAULTS_VERYHIGH 128

// GRAPHICS

#define PLEX_MEMLIMIT_DRAWLIST_LOW 128
#define PLEX_MEMLIMIT_DRAWLIST_MEDIUM 512
#define PLEX_MEMLIMIT_DRAWLIST_HIGH 1024
#define PLEX_MEMLIMIT_DRAWLIST_VERYHIGH 2048

#define PLEX_MEMLIMIT_FRAMEPRELOAD_LOW 8
#define PLEX_MEMLIMIT_FRAMEPRELOAD_MEDIUM 16
#define PLEX_MEMLIMIT_FRAMEPRELOAD_HIGH 32
#define PLEX_MEMLIMIT_FRAMEPRELOAD_VERYHIGH 128

#define PLEX_MEMLIMIT_ANIMATIONMAX_LOW 4
#define PLEX_MEMLIMIT_ANIMATIONMAX_MEDIUM 8
#define PLEX_MEMLIMIT_ANIMATIONMAX_HIGH 32
#define PLEX_MEMLIMIT_ANIMATIONMAX_VERYHIGH 128

#define PLEX_MEMLIMIT_SCREENEFFECTS_LOW 4
#define PLEX_MEMLIMIT_SCREENEFFECTS_MEDIUM 8
#define PLEX_MEMLIMIT_SCREENEFFECTS_HIGH 32
#define PLEX_MEMLIMIT_SCREENEFFECTS_VERYHIGH 128

// TEXTURE

#define PLEX_MEMLIMIT_TEXTUREPRELOAD_LOW 8
#define PLEX_MEMLIMIT_TEXTUREPRELOAD_MEDIUM 32
#define PLEX_MEMLIMIT_TEXTUREPRELOAD_HIGH 128
#define PLEX_MEMLIMIT_TEXTUREPRELOAD_VERYHIGH 256

// FILE PARSING

#define PLEX_MEMLIMIT_LINEPARSE_LOW 4
#define PLEX_MEMLIMIT_LINEPARSE_MEDIUM 16
#define PLEX_MEMLIMIT_LINEPARSE_HIGH 32
#define PLEX_MEMLIMIT_LINEPARSE_VERYHIGH 128

#define PLEX_MEMLIMIT_TOKENLIMIT_LOW 4
#define PLEX_MEMLIMIT_TOKENLIMIT_MEDIUM 8
#define PLEX_MEMLIMIT_TOKENLIMIT_HIGH 16
#define PLEX_MEMLIMIT_TOKENLIMIT_VERYHIGH 128

// SPRITE THEATER

#define PLEX_MEMLIMIT_SPRITETHEATER_SLIDE_LOW 4
#define PLEX_MEMLIMIT_SPRITETHEATER_SLIDE_MEDIUM 8
#define PLEX_MEMLIMIT_SPRITETHEATER_SLIDE_HIGH 32
#define PLEX_MEMLIMIT_SPRITETHEATER_SLIDE_VERYHIGH 128

#define PLEX_MEMLIMIT_SPRITETHEATER_ACTOR_LOW 4
#define PLEX_MEMLIMIT_SPRITETHEATER_ACTOR_MEDIUM 8
#define PLEX_MEMLIMIT_SPRITETHEATER_ACTOR_HIGH 32
#define PLEX_MEMLIMIT_SPRITETHEATER_ACTOR_VERYHIGH 128

#define PLEX_MEMLIMIT_SPRITETHEATER_ACTORCHANGE_LOW 4
#define PLEX_MEMLIMIT_SPRITETHEATER_ACTORCHANGE_MEDIUM 8
#define PLEX_MEMLIMIT_SPRITETHEATER_ACTORCHANGE_HIGH 32
#define PLEX_MEMLIMIT_SPRITETHEATER_ACTORCHANGE_VERYHIGH 128

#define PLEX_MEMLIMIT_SPRITETHEATER_MUSICCHANGE_LOW 4
#define PLEX_MEMLIMIT_SPRITETHEATER_MUSICCHANGE_MEDIUM 8
#define PLEX_MEMLIMIT_SPRITETHEATER_MUSICCHANGE_HIGH 32
#define PLEX_MEMLIMIT_SPRITETHEATER_MUSICCHANGE_VERYHIGH 128

// GENERATOR

#define PLEX_MEMLIMIT_GENSTART_LOW 8
#define PLEX_MEMLIMIT_GENSTART_MEDIUM 16
#define PLEX_MEMLIMIT_GENSTART_HIGH 32
#define PLEX_MEMLIMIT_GENSTART_VERYHIGH 128

// PROMINENCE MACHINE

#define PLEX_MEMLIMIT_PROMPRELOAD_LOW 8
#define PLEX_MEMLIMIT_PROMPRELOAD_MEDIUM 16
#define PLEX_MEMLIMIT_PROMPRELOAD_HIGH 32
#define PLEX_MEMLIMIT_PROMPRELOAD_VERYHIGH 128

#ifdef __cplusplus
extern "C"
{
#endif
	extern void PLEX_setMemProfile(const uint8_t profile);

	// MEMORY

	extern size_t PLEX_getMemProfilePreload();
	extern size_t PLEX_getMemProfileMemReuse();

	// DEFAULTS

	extern size_t PLEX_getMemProfileDefaultPreload();

	// GRAPHICS

	extern size_t PLEX_getMemProfileDrawlistPreload();

	// ANIMATION

	extern size_t PLEX_getMemProfileFramePreload();
	extern size_t PLEX_getMemProfileAnimationPreload();

	// SCREEN EFFECTS

	extern size_t PLEX_getMemProfileScreenEffectsPreload();

	// TEXTURE

	extern size_t PLEX_getMemProfileTexturePreload();

	// FILE PARSE

	extern size_t PLEX_getMemProfileLineParsePreload();
	extern size_t PLEX_getMemProfileTokenPreload();

	// SPRITE THEATER

	extern size_t PLEX_getMemProfileSpriteTheaterSlide();
	extern size_t PLEX_getMemProfileActor();
	extern size_t PLEX_getMemProfileActorChange();
	extern size_t PLEX_getMemProfileMusicChange();

	// GENERATOR

	extern size_t PLEX_getMemProfileGenStart();

	// PRELOAD

	extern size_t PLEX_getMemProfilePromPreload();

#ifdef __cplusplus
}
#endif


#endif
