#ifndef PLEX_MM_COMMON_FILEPATHS_H
#define PLEX_MM_COMMON_FILEPATHS_H

#include "meta/language.h"

// GRAPHICS -----------------------------------------------------------------------------------------------------------------------------------------------

// SPRITE THEATER

#define MMS_FILEPATH_TEX_SELECTIONFONT "resources/common/graphics/spritetheater/selectionfont.png"
#define MMS_FILEPATH_TEX_STAGELABEL "resources/common/graphics/spritetheater/stagelabel.png"
#define MMS_FILEPATH_TEX_BUBBLE "resources/common/graphics/spritetheater/bubble.png"
#define MMS_FILEPATH_TEX_ARROW "resources/common/graphics/spritetheater/arrow.png"

// SPRITES

// PAMALEANA

#define MMS_FILEPATH_TEX_PAMALEANASPRITEPLATE "resources/common/graphics/sprites/pamaleana/pamaleanaSpritesplate.png"

// EXTRAPLOCAN

#define MMS_FILEPATH_TEX_EXTRAPLOCANSPRITEPLATE "resources/common/graphics/sprites/extraplocan/extraplocanSpritesplate.png"

// MR. VENARIUS

#define MMS_FILEPATH_TEX_MRVENARIUS "resources/common/graphics/sprites/mrvenarius/mrvenariusSpritesplate.png"

// LEVINE

#define MMS_FILEPATH_TEX_LEVINESPRITEPLATE "resources/common/graphics/sprites/levine/levineSpritesplate.png"

// SPRITE THEATER BACKDROPS

#define MMS_FILEPATH_TEX_OFFICEBACK "resources/common/graphics/backdrops/pampamsoffice.png"

// SOUND -----------------------------------------------------------------------------------------------------------------------------------------------

// SOUND EFFECTS

#define MM_COMMON_SOUNDPATH_KNOCKING "resources/common/sound/soundeffects/knocking.wav"
#define MM_COMMON_SOUNDPATH_SHOCKCUE "resources/common/sound/soundeffects/shockcue.wav"
#define MM_COMMON_SOUNDPATH_SURREALHONKHONK "resources/common/sound/soundeffects/surrealhorn.wav"

#define MM_COMMON_SOUNDPATH_PAMENGINEREV "resources/common/sound/soundeffects/pamenginerev.wav"
#define MM_COMMON_SOUNDPATH_PAMENGINERUN "resources/common/sound/soundeffects/pamenginerun.wav"
#define MM_COMMON_SOUNDPATH_PAMENGINESTRUGGLE "resources/common/sound/soundeffects/pamenginestruggle.wav"

#define MM_COMMON_SOUNDPATH_CRASH "resources/common/sound/soundeffects/crash.wav"
#define MM_COMMON_SOUNDPATH_SURREALGLASSCRACK "resources/common/sound/soundeffects/surrealglasscrack.wav"

#define MM_COMMON_SOUNDPATH_ZOOMBY "resources/common/sound/soundeffects/zoomby.wav"

// MAIN THEME

#define MM_COMMON_MUSICPATH_MAIN_LOOP "resources/common/sound/themes/main/loop.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWA0 "resources/common/sound/themes/main/rawA0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA1 "resources/common/sound/themes/main/rawA1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA2 "resources/common/sound/themes/main/rawA2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA3 "resources/common/sound/themes/main/rawA3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA4 "resources/common/sound/themes/main/rawA4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA5 "resources/common/sound/themes/main/rawA5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA6 "resources/common/sound/themes/main/rawA6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA7 "resources/common/sound/themes/main/rawA7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA8 "resources/common/sound/themes/main/rawA8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA9 "resources/common/sound/themes/main/rawA9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA10 "resources/common/sound/themes/main/rawA10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA11 "resources/common/sound/themes/main/rawA11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA12 "resources/common/sound/themes/main/rawA12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA13 "resources/common/sound/themes/main/rawA13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA14 "resources/common/sound/themes/main/rawA14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA15 "resources/common/sound/themes/main/rawA15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA16 "resources/common/sound/themes/main/rawA16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA17 "resources/common/sound/themes/main/rawA17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA18 "resources/common/sound/themes/main/rawA18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA19 "resources/common/sound/themes/main/rawA19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA20 "resources/common/sound/themes/main/rawA20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA21 "resources/common/sound/themes/main/rawA21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA22 "resources/common/sound/themes/main/rawA22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA23 "resources/common/sound/themes/main/rawA23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA24 "resources/common/sound/themes/main/rawA24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA25 "resources/common/sound/themes/main/rawA25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA26 "resources/common/sound/themes/main/rawA26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA27 "resources/common/sound/themes/main/rawA27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA28 "resources/common/sound/themes/main/rawA28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA29 "resources/common/sound/themes/main/rawA29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA30 "resources/common/sound/themes/main/rawA30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA31 "resources/common/sound/themes/main/rawA31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA32 "resources/common/sound/themes/main/rawA32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA33 "resources/common/sound/themes/main/rawA33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA34 "resources/common/sound/themes/main/rawA34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA35 "resources/common/sound/themes/main/rawA35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA36 "resources/common/sound/themes/main/rawA36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA37 "resources/common/sound/themes/main/rawA37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA38 "resources/common/sound/themes/main/rawA38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA39 "resources/common/sound/themes/main/rawA39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA40 "resources/common/sound/themes/main/rawA40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA41 "resources/common/sound/themes/main/rawA41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA42 "resources/common/sound/themes/main/rawA42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA43 "resources/common/sound/themes/main/rawA43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA44 "resources/common/sound/themes/main/rawA44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA45 "resources/common/sound/themes/main/rawA45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA46 "resources/common/sound/themes/main/rawA46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA47 "resources/common/sound/themes/main/rawA47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA48 "resources/common/sound/themes/main/rawA48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWA49 "resources/common/sound/themes/main/rawA49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWB0 "resources/common/sound/themes/main/rawB0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB1 "resources/common/sound/themes/main/rawB1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB2 "resources/common/sound/themes/main/rawB2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB3 "resources/common/sound/themes/main/rawB3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB4 "resources/common/sound/themes/main/rawB4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB5 "resources/common/sound/themes/main/rawB5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB6 "resources/common/sound/themes/main/rawB6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB7 "resources/common/sound/themes/main/rawB7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB8 "resources/common/sound/themes/main/rawB8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB9 "resources/common/sound/themes/main/rawB9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB10 "resources/common/sound/themes/main/rawB10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB11 "resources/common/sound/themes/main/rawB11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB12 "resources/common/sound/themes/main/rawB12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB13 "resources/common/sound/themes/main/rawB13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB14 "resources/common/sound/themes/main/rawB14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB15 "resources/common/sound/themes/main/rawB15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB16 "resources/common/sound/themes/main/rawB16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB17 "resources/common/sound/themes/main/rawB17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB18 "resources/common/sound/themes/main/rawB18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB19 "resources/common/sound/themes/main/rawB19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB20 "resources/common/sound/themes/main/rawB20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB21 "resources/common/sound/themes/main/rawB21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB22 "resources/common/sound/themes/main/rawB22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB23 "resources/common/sound/themes/main/rawB23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB24 "resources/common/sound/themes/main/rawB24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB25 "resources/common/sound/themes/main/rawB25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB26 "resources/common/sound/themes/main/rawB26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB27 "resources/common/sound/themes/main/rawB27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB28 "resources/common/sound/themes/main/rawB28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB29 "resources/common/sound/themes/main/rawB29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB30 "resources/common/sound/themes/main/rawB30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB31 "resources/common/sound/themes/main/rawB31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB32 "resources/common/sound/themes/main/rawB32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB33 "resources/common/sound/themes/main/rawB33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB34 "resources/common/sound/themes/main/rawB34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB35 "resources/common/sound/themes/main/rawB35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB36 "resources/common/sound/themes/main/rawB36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB37 "resources/common/sound/themes/main/rawB37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB38 "resources/common/sound/themes/main/rawB38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB39 "resources/common/sound/themes/main/rawB39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB40 "resources/common/sound/themes/main/rawB40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB41 "resources/common/sound/themes/main/rawB41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB42 "resources/common/sound/themes/main/rawB42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB43 "resources/common/sound/themes/main/rawB43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB44 "resources/common/sound/themes/main/rawB44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB45 "resources/common/sound/themes/main/rawB45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB46 "resources/common/sound/themes/main/rawB46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB47 "resources/common/sound/themes/main/rawB47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB48 "resources/common/sound/themes/main/rawB48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWB49 "resources/common/sound/themes/main/rawB49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWC0 "resources/common/sound/themes/main/rawC0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC1 "resources/common/sound/themes/main/rawC1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC2 "resources/common/sound/themes/main/rawC2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC3 "resources/common/sound/themes/main/rawC3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC4 "resources/common/sound/themes/main/rawC4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC5 "resources/common/sound/themes/main/rawC5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC6 "resources/common/sound/themes/main/rawC6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC7 "resources/common/sound/themes/main/rawC7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC8 "resources/common/sound/themes/main/rawC8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC9 "resources/common/sound/themes/main/rawC9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC10 "resources/common/sound/themes/main/rawC10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC11 "resources/common/sound/themes/main/rawC11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC12 "resources/common/sound/themes/main/rawC12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC13 "resources/common/sound/themes/main/rawC13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC14 "resources/common/sound/themes/main/rawC14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC15 "resources/common/sound/themes/main/rawC15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC16 "resources/common/sound/themes/main/rawC16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC17 "resources/common/sound/themes/main/rawC17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC18 "resources/common/sound/themes/main/rawC18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC19 "resources/common/sound/themes/main/rawC19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC20 "resources/common/sound/themes/main/rawC20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC21 "resources/common/sound/themes/main/rawC21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC22 "resources/common/sound/themes/main/rawC22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC23 "resources/common/sound/themes/main/rawC23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC24 "resources/common/sound/themes/main/rawC24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC25 "resources/common/sound/themes/main/rawC25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC26 "resources/common/sound/themes/main/rawC26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC27 "resources/common/sound/themes/main/rawC27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC28 "resources/common/sound/themes/main/rawC28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC29 "resources/common/sound/themes/main/rawC29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC30 "resources/common/sound/themes/main/rawC30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC31 "resources/common/sound/themes/main/rawC31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC32 "resources/common/sound/themes/main/rawC32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC33 "resources/common/sound/themes/main/rawC33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC34 "resources/common/sound/themes/main/rawC34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC35 "resources/common/sound/themes/main/rawC35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC36 "resources/common/sound/themes/main/rawC36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC37 "resources/common/sound/themes/main/rawC37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC38 "resources/common/sound/themes/main/rawC38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC39 "resources/common/sound/themes/main/rawC39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC40 "resources/common/sound/themes/main/rawC40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC41 "resources/common/sound/themes/main/rawC41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC42 "resources/common/sound/themes/main/rawC42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC43 "resources/common/sound/themes/main/rawC43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC44 "resources/common/sound/themes/main/rawC44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC45 "resources/common/sound/themes/main/rawC45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC46 "resources/common/sound/themes/main/rawC46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC47 "resources/common/sound/themes/main/rawC47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC48 "resources/common/sound/themes/main/rawC48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWC49 "resources/common/sound/themes/main/rawC49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWD0 "resources/common/sound/themes/main/rawD0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD1 "resources/common/sound/themes/main/rawD1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD2 "resources/common/sound/themes/main/rawD2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD3 "resources/common/sound/themes/main/rawD3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD4 "resources/common/sound/themes/main/rawD4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD5 "resources/common/sound/themes/main/rawD5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD6 "resources/common/sound/themes/main/rawD6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD7 "resources/common/sound/themes/main/rawD7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD8 "resources/common/sound/themes/main/rawD8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD9 "resources/common/sound/themes/main/rawD9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD10 "resources/common/sound/themes/main/rawD10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD11 "resources/common/sound/themes/main/rawD11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD12 "resources/common/sound/themes/main/rawD12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD13 "resources/common/sound/themes/main/rawD13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD14 "resources/common/sound/themes/main/rawD14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD15 "resources/common/sound/themes/main/rawD15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD16 "resources/common/sound/themes/main/rawD16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD17 "resources/common/sound/themes/main/rawD17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD18 "resources/common/sound/themes/main/rawD18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD19 "resources/common/sound/themes/main/rawD19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD20 "resources/common/sound/themes/main/rawD20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD21 "resources/common/sound/themes/main/rawD21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD22 "resources/common/sound/themes/main/rawD22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD23 "resources/common/sound/themes/main/rawD23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD24 "resources/common/sound/themes/main/rawD24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD25 "resources/common/sound/themes/main/rawD25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD26 "resources/common/sound/themes/main/rawD26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD27 "resources/common/sound/themes/main/rawD27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD28 "resources/common/sound/themes/main/rawD28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD29 "resources/common/sound/themes/main/rawD29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD30 "resources/common/sound/themes/main/rawD30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD31 "resources/common/sound/themes/main/rawD31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD32 "resources/common/sound/themes/main/rawD32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD33 "resources/common/sound/themes/main/rawD33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD34 "resources/common/sound/themes/main/rawD34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD35 "resources/common/sound/themes/main/rawD35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD36 "resources/common/sound/themes/main/rawD36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD37 "resources/common/sound/themes/main/rawD37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD38 "resources/common/sound/themes/main/rawD38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD39 "resources/common/sound/themes/main/rawD39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD40 "resources/common/sound/themes/main/rawD40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD41 "resources/common/sound/themes/main/rawD41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD42 "resources/common/sound/themes/main/rawD42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD43 "resources/common/sound/themes/main/rawD43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD44 "resources/common/sound/themes/main/rawD44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD45 "resources/common/sound/themes/main/rawD45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD46 "resources/common/sound/themes/main/rawD46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD47 "resources/common/sound/themes/main/rawD47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD48 "resources/common/sound/themes/main/rawD48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWD49 "resources/common/sound/themes/main/rawD49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWE0 "resources/common/sound/themes/main/rawE0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE1 "resources/common/sound/themes/main/rawE1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE2 "resources/common/sound/themes/main/rawE2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE3 "resources/common/sound/themes/main/rawE3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE4 "resources/common/sound/themes/main/rawE4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE5 "resources/common/sound/themes/main/rawE5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE6 "resources/common/sound/themes/main/rawE6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE7 "resources/common/sound/themes/main/rawE7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE8 "resources/common/sound/themes/main/rawE8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE9 "resources/common/sound/themes/main/rawE9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE10 "resources/common/sound/themes/main/rawE10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE11 "resources/common/sound/themes/main/rawE11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE12 "resources/common/sound/themes/main/rawE12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE13 "resources/common/sound/themes/main/rawE13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE14 "resources/common/sound/themes/main/rawE14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE15 "resources/common/sound/themes/main/rawE15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE16 "resources/common/sound/themes/main/rawE16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE17 "resources/common/sound/themes/main/rawE17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE18 "resources/common/sound/themes/main/rawE18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE19 "resources/common/sound/themes/main/rawE19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE20 "resources/common/sound/themes/main/rawE20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE21 "resources/common/sound/themes/main/rawE21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE22 "resources/common/sound/themes/main/rawE22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE23 "resources/common/sound/themes/main/rawE23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE24 "resources/common/sound/themes/main/rawE24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE25 "resources/common/sound/themes/main/rawE25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE26 "resources/common/sound/themes/main/rawE26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE27 "resources/common/sound/themes/main/rawE27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE28 "resources/common/sound/themes/main/rawE28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE29 "resources/common/sound/themes/main/rawE29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE30 "resources/common/sound/themes/main/rawE30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE31 "resources/common/sound/themes/main/rawE31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE32 "resources/common/sound/themes/main/rawE32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE33 "resources/common/sound/themes/main/rawE33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE34 "resources/common/sound/themes/main/rawE34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE35 "resources/common/sound/themes/main/rawE35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE36 "resources/common/sound/themes/main/rawE36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE37 "resources/common/sound/themes/main/rawE37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE38 "resources/common/sound/themes/main/rawE38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE39 "resources/common/sound/themes/main/rawE39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE40 "resources/common/sound/themes/main/rawE40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE41 "resources/common/sound/themes/main/rawE41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE42 "resources/common/sound/themes/main/rawE42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE43 "resources/common/sound/themes/main/rawE43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE44 "resources/common/sound/themes/main/rawE44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE45 "resources/common/sound/themes/main/rawE45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE46 "resources/common/sound/themes/main/rawE46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE47 "resources/common/sound/themes/main/rawE47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE48 "resources/common/sound/themes/main/rawE48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWE49 "resources/common/sound/themes/main/rawE49.wav"

#define MM_COMMON_MUSICPATH_MAIN_RAWF0 "resources/common/sound/themes/main/rawF0.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF1 "resources/common/sound/themes/main/rawF1.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF2 "resources/common/sound/themes/main/rawF2.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF3 "resources/common/sound/themes/main/rawF3.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF4 "resources/common/sound/themes/main/rawF4.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF5 "resources/common/sound/themes/main/rawF5.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF6 "resources/common/sound/themes/main/rawF6.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF7 "resources/common/sound/themes/main/rawF7.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF8 "resources/common/sound/themes/main/rawF8.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF9 "resources/common/sound/themes/main/rawF9.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF10 "resources/common/sound/themes/main/rawF10.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF11 "resources/common/sound/themes/main/rawF11.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF12 "resources/common/sound/themes/main/rawF12.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF13 "resources/common/sound/themes/main/rawF13.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF14 "resources/common/sound/themes/main/rawF14.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF15 "resources/common/sound/themes/main/rawF15.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF16 "resources/common/sound/themes/main/rawF16.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF17 "resources/common/sound/themes/main/rawF17.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF18 "resources/common/sound/themes/main/rawF18.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF19 "resources/common/sound/themes/main/rawF19.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF20 "resources/common/sound/themes/main/rawF20.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF21 "resources/common/sound/themes/main/rawF21.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF22 "resources/common/sound/themes/main/rawF22.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF23 "resources/common/sound/themes/main/rawF23.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF24 "resources/common/sound/themes/main/rawF24.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF25 "resources/common/sound/themes/main/rawF25.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF26 "resources/common/sound/themes/main/rawF26.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF27 "resources/common/sound/themes/main/rawF27.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF28 "resources/common/sound/themes/main/rawF28.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF29 "resources/common/sound/themes/main/rawF29.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF30 "resources/common/sound/themes/main/rawF30.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF31 "resources/common/sound/themes/main/rawF31.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF32 "resources/common/sound/themes/main/rawF32.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF33 "resources/common/sound/themes/main/rawF33.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF34 "resources/common/sound/themes/main/rawF34.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF35 "resources/common/sound/themes/main/rawF35.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF36 "resources/common/sound/themes/main/rawF36.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF37 "resources/common/sound/themes/main/rawF37.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF38 "resources/common/sound/themes/main/rawF38.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF39 "resources/common/sound/themes/main/rawF39.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF40 "resources/common/sound/themes/main/rawF40.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF41 "resources/common/sound/themes/main/rawF41.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF42 "resources/common/sound/themes/main/rawF42.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF43 "resources/common/sound/themes/main/rawF43.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF44 "resources/common/sound/themes/main/rawF44.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF45 "resources/common/sound/themes/main/rawF45.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF46 "resources/common/sound/themes/main/rawF46.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF47 "resources/common/sound/themes/main/rawF47.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF48 "resources/common/sound/themes/main/rawF48.wav"
#define MM_COMMON_MUSICPATH_MAIN_RAWF49 "resources/common/sound/themes/main/rawF49.wav"

// EXTRAPLOCAN THEME

#define MM_COMMON_MUSICPATH_EXTRAP_INTROORCHA "resources/common/sound/themes/extraplocan/introOrchA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_INTROORCHB "resources/common/sound/themes/extraplocan/introOrchB.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_ORCHA "resources/common/sound/themes/extraplocan/orchA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHB "resources/common/sound/themes/extraplocan/orchB.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHC "resources/common/sound/themes/extraplocan/orchC.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHD "resources/common/sound/themes/extraplocan/orchD.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_ORCHE "resources/common/sound/themes/extraplocan/orchE.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_INTROPERCA "resources/common/sound/themes/extraplocan/introPercA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_INTROPERCB "resources/common/sound/themes/extraplocan/introPercB.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_PERCA "resources/common/sound/themes/extraplocan/percA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCB "resources/common/sound/themes/extraplocan/percB.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCC "resources/common/sound/themes/extraplocan/percC.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCD "resources/common/sound/themes/extraplocan/percD.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_PERCE "resources/common/sound/themes/extraplocan/percE.wav"

#define MM_COMMON_MUSICPATH_EXTRAP_VOXA "resources/common/sound/themes/extraplocan/voxA.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXB "resources/common/sound/themes/extraplocan/voxB.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXC "resources/common/sound/themes/extraplocan/voxC.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXD "resources/common/sound/themes/extraplocan/voxD.wav"
#define MM_COMMON_MUSICPATH_EXTRAP_VOXE "resources/common/sound/themes/extraplocan/voxE.wav"

// NEWSROOM

#define MM_COMMON_MUSICPATH_NEWSROOM_DRUM0 "resources/common/sound/themes/newsroom/D0.wav"
#define MM_COMMON_MUSICPATH_NEWSROOM_DRUM1 "resources/common/sound/themes/newsroom/D1.wav"

#define MM_COMMON_MUSICPATH_NEWSROOM_TRUMPET0 "resources/common/sound/themes/newsroom/T0.wav"
#define MM_COMMON_MUSICPATH_NEWSROOM_TRUMPET1 "resources/common/sound/themes/newsroom/T1.wav"

#define MM_COMMON_MUSICPATH_NEWSROOM_SYNTHA "resources/common/sound/themes/newsroom/SA.wav"
#define MM_COMMON_MUSICPATH_NEWSROOM_SYNTHB "resources/common/sound/themes/newsroom/SB.wav"

// COMEDY

#define MM_COMMON_MUSICPATH_COMEDY_BC0 "resources/common/sound/themes/comedy/BC0.wav"
#define MM_COMMON_MUSICPATH_COMEDY_BC1 "resources/common/sound/themes/comedy/BC1.wav"
#define MM_COMMON_MUSICPATH_COMEDY_BC2 "resources/common/sound/themes/comedy/BC2.wav"
#define MM_COMMON_MUSICPATH_COMEDY_BC3 "resources/common/sound/themes/comedy/BC3.wav"

#define MM_COMMON_MUSICPATH_COMEDY_D0 "resources/common/sound/themes/comedy/D0.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D1 "resources/common/sound/themes/comedy/D1.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D2 "resources/common/sound/themes/comedy/D2.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D3 "resources/common/sound/themes/comedy/D3.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D4A "resources/common/sound/themes/comedy/D4A.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D4B "resources/common/sound/themes/comedy/D4B.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D5 "resources/common/sound/themes/comedy/D5.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D6A "resources/common/sound/themes/comedy/D6A.wav"
#define MM_COMMON_MUSICPATH_COMEDY_D6B "resources/common/sound/themes/comedy/D6B.wav"

#define MM_COMMON_MUSICPATH_COMEDY_O0 "resources/common/sound/themes/comedy/O0.wav"
#define MM_COMMON_MUSICPATH_COMEDY_O1 "resources/common/sound/themes/comedy/O1.wav"
#define MM_COMMON_MUSICPATH_COMEDY_O3 "resources/common/sound/themes/comedy/O3.wav"

// PANIC

#define MM_COMMON_MUSICPATH_PANIC_AMBIENCE "resources/common/sound/themes/panic/ambience.wav"

#define MM_COMMON_MUSICPATH_PANIC_DRUMS "resources/common/sound/themes/panic/drum.wav"

#define MM_COMMON_MUSICPATH_PANIC_PIANO "resources/common/sound/themes/panic/piano.wav"

#define MM_COMMON_MUSICPATH_PANIC_TROMBONE "resources/common/sound/themes/panic/trombone.wav"

#define MM_COMMON_MUSICPATH_PANIC_AMSYNTH0 "resources/common/sound/themes/panic/amsynth0.wav"
#define MM_COMMON_MUSICPATH_PANIC_AMSYNTH1 "resources/common/sound/themes/panic/amsynth1.wav"

#define MM_COMMON_MUSICPATH_PANIC_SAXREP0 "resources/common/sound/themes/panic/saxrep0.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXREP1 "resources/common/sound/themes/panic/saxrep1.wav"

#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO0 "resources/common/sound/themes/panic/saxsolo0.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO1 "resources/common/sound/themes/panic/saxsolo1.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO2 "resources/common/sound/themes/panic/saxsolo2.wav"
#define MM_COMMON_MUSICPATH_PANIC_SAXSOLO3 "resources/common/sound/themes/panic/saxsolo3.wav"

// DARK CITY

#define MM_COMMON_MUSICPATH_DARKCITY_A0 "resources/common/sound/themes/darkcity/A0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_A1 "resources/common/sound/themes/darkcity/A1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_B0 "resources/common/sound/themes/darkcity/B0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_B1 "resources/common/sound/themes/darkcity/B1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_C0 "resources/common/sound/themes/darkcity/C0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_C1 "resources/common/sound/themes/darkcity/C1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_D0 "resources/common/sound/themes/darkcity/D0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_D1 "resources/common/sound/themes/darkcity/D1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_E0 "resources/common/sound/themes/darkcity/E0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_E1 "resources/common/sound/themes/darkcity/E1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_F0 "resources/common/sound/themes/darkcity/F0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_F1 "resources/common/sound/themes/darkcity/F1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_G0 "resources/common/sound/themes/darkcity/G0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_G1 "resources/common/sound/themes/darkcity/G1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_H0 "resources/common/sound/themes/darkcity/H0.wav"
#define MM_COMMON_MUSICPATH_DARKCITY_H1 "resources/common/sound/themes/darkcity/H1.wav"

#define MM_COMMON_MUSICPATH_DARKCITY_I0 "resources/common/sound/themes/darkcity/I0.wav"

// SUSPENSE THEME

#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETD "resources/common/sound/themes/suspense/clarinetd.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETE "resources/common/sound/themes/suspense/clarinete.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETF "resources/common/sound/themes/suspense/clarinetf.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_CLARINETG "resources/common/sound/themes/suspense/clarinetg.wav"

#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSA "resources/common/sound/themes/suspense/percussa.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSB "resources/common/sound/themes/suspense/percussb.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSC "resources/common/sound/themes/suspense/percussc.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSD "resources/common/sound/themes/suspense/percussd.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSE "resources/common/sound/themes/suspense/percusse.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSF "resources/common/sound/themes/suspense/percussf.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PERCUSSG "resources/common/sound/themes/suspense/percussg.wav"

#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINA "resources/common/sound/themes/suspense/violina.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINB "resources/common/sound/themes/suspense/violinb.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINC "resources/common/sound/themes/suspense/violinc.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLIND "resources/common/sound/themes/suspense/violind.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINE "resources/common/sound/themes/suspense/violine.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLINF "resources/common/sound/themes/suspense/violinf.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_VIOLING "resources/common/sound/themes/suspense/violing.wav"

#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOA "resources/common/sound/themes/suspense/pianoa.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOC "resources/common/sound/themes/suspense/pianoc.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOD "resources/common/sound/themes/suspense/pianod.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOE "resources/common/sound/themes/suspense/pianoe.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOF "resources/common/sound/themes/suspense/pianof.wav"
#define MM_COMMON_MUSICPATH_SUSPENSE_PIANOG "resources/common/sound/themes/suspense/pianog.wav"

// PAMALEANA THEME

#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOA "resources/common/sound/themes/pamaleana/P0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOB "resources/common/sound/themes/pamaleana/P1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOC "resources/common/sound/themes/pamaleana/P2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOD "resources/common/sound/themes/pamaleana/P3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOE "resources/common/sound/themes/pamaleana/P4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOF "resources/common/sound/themes/pamaleana/P5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOG "resources/common/sound/themes/pamaleana/P6.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOH "resources/common/sound/themes/pamaleana/P7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOI "resources/common/sound/themes/pamaleana/P8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_PIANOJ "resources/common/sound/themes/pamaleana/P9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSA "resources/common/sound/themes/pamaleana/CB0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSB "resources/common/sound/themes/pamaleana/CB1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSC "resources/common/sound/themes/pamaleana/CB2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSD "resources/common/sound/themes/pamaleana/CB3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSE "resources/common/sound/themes/pamaleana/CB4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSF "resources/common/sound/themes/pamaleana/CB5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSH "resources/common/sound/themes/pamaleana/CB7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSI "resources/common/sound/themes/pamaleana/CB8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_CONTRABASSJ "resources/common/sound/themes/pamaleana/CB9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINA "resources/common/sound/themes/pamaleana/V0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINB "resources/common/sound/themes/pamaleana/V1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINC "resources/common/sound/themes/pamaleana/V2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLIND "resources/common/sound/themes/pamaleana/V3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINE "resources/common/sound/themes/pamaleana/V4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINF "resources/common/sound/themes/pamaleana/V5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINH "resources/common/sound/themes/pamaleana/V7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINI "resources/common/sound/themes/pamaleana/V8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_VIOLINJ "resources/common/sound/themes/pamaleana/V9.wav"

#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAA "resources/common/sound/themes/pamaleana/M0.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAB "resources/common/sound/themes/pamaleana/M1.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAC "resources/common/sound/themes/pamaleana/M2.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAD "resources/common/sound/themes/pamaleana/M3.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAE "resources/common/sound/themes/pamaleana/M4.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAF "resources/common/sound/themes/pamaleana/M5.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAH "resources/common/sound/themes/pamaleana/M7.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAI "resources/common/sound/themes/pamaleana/M8.wav"
#define MM_COMMON_MUSICPATH_PAMALEANA_MARIMBAJ "resources/common/sound/themes/pamaleana/M9.wav"

// DAYDAY THEME

#define MM_COMMON_MUSICPATH_DAYTODAY_DRUM0 "resources/common/sound/themes/daytoday/drum0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_DRUM1 "resources/common/sound/themes/daytoday/drum1.wav"

#define MM_COMMON_MUSICPATH_DAYTODAY_MONOSYNTH0 "resources/common/sound/themes/daytoday/monosynth0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_MONOSYNTH1 "resources/common/sound/themes/daytoday/monosynth1.wav"

#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANA0 "resources/common/sound/themes/daytoday/organA0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANA1 "resources/common/sound/themes/daytoday/organA1.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANA2 "resources/common/sound/themes/daytoday/organA2.wav"

#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANB0 "resources/common/sound/themes/daytoday/organB0.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANB1 "resources/common/sound/themes/daytoday/organB1.wav"
#define MM_COMMON_MUSICPATH_DAYTODAY_ORGANB2 "resources/common/sound/themes/daytoday/organB2.wav"

// DREAM THEME

#define MM_COMMON_MUSICPATH_DREAM_HARPA "resources/common/sound/themes/dream/harp0.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPB "resources/common/sound/themes/dream/harp1.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPC "resources/common/sound/themes/dream/harp2.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPD "resources/common/sound/themes/dream/harp3.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPE "resources/common/sound/themes/dream/harp4.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPF "resources/common/sound/themes/dream/harp5.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPG "resources/common/sound/themes/dream/harp6.wav"
#define MM_COMMON_MUSICPATH_DREAM_HARPH "resources/common/sound/themes/dream/harp7.wav"

#define MM_COMMON_MUSICPATH_DREAM_LOOP "resources/common/sound/themes/dream/dreamloop.wav"

#endif
