#ifndef MMS1_META_H
#define MMS1_META_H

#include "plex.h"

#include "mmcommon.h"

#include "chapters/mms0.h"
#include "chapters/unlock.h"

// COLLISION

#define MM1_OBSTRUCTIONVELOCITYLOW 0.05
#define MM1_OBSTRUCTIONVELOCITYBASE 40

#define MMS1_OBSTUCTION_LIMIT 32
#define MMS1_ANGLERISE 0.5
#define MMS1_ACCEL_MAX 200.0

#define MMS1_DRIFTSPEED 4
#define MMS1_DRIFTHEALTHEFFECT 0.05

#define MMS1_BOUNDARYRANGE 1

#define MMS1_DRAWTRANSLATE 0.75

#define MMS1_ACCELRATE 8
#define MMS1_FASTACCELRATE 2

#define MMS1_DEACCELRATE 2
#define MMS1_CAPDEACCELRATE 2

#define MMS1_ACCELFASTCAP 25
#define MMS1_ACCELFASTERCAP 50
#define MMS1_ACCELFASTESTCAP 100

#define MMS1_STARTACCEL 50

// PAMALEANA AND CAR

#define MMS1_FASTESTCYCLE_PAMALEANAANIMATION 100
#define MMS1_SLOWESTCYCLE_PAMALEANAANIMATION 1000

#define MMS1_FASTESTCYCLE_CARWINGANIMATION 200
#define MMS1_SLOWESTCYCLE_CARWINGANIMATION 800

#define MMS1_FASTESTCYCLE_CARBACKANIMATION 50
#define MMS1_SLOWESTCYCLE_CARBACKANIMATION 200

#define MMS1_SPRITELAYER_WING 0
#define MMS1_SPRITELAYER_BACK 1
#define MMS1_SPRITELAYER_PAMALEANA 2
#define MMS1_SPRITELAYER_FRONT 3
#define MMS1_SPRITELAYER_WINDSHIELD 6

// ENVIRONMENT

#define MMS1_FASTESTCYCLE_DOMEANIMATION 50
#define MMS1_SLOWESTCYCLE_DOMEANIMATION 400

#define MMS1_FASTESTCYCLE_ROADANIMATION 50
#define MMS1_SLOWESTCYCLE_ROADANIMATION 400

#define MMS1_FASTESTCYCLE_ROAD4ANIMATION 200
#define MMS1_SLOWESTCYCLE_ROAD4ANIMATION 1600

#define MMS1_MENULAYER 1
#define MMS1_OVERROADLAYER 5000
#define MMS1_ENDLAYER 10000

#define MMS1_LANE_MAX 4

// OBSTRUCTIONS

#define MMS1_PHASE_MAX 4

#define MMS1_SPRITELAYER_OBSTRUCTION 7

// MINIGAME 1

#define MMS1_FULLDIST 14000.0
#define MMS1_UNREALISTICALLYLATE 220.0
#define MMS1_UNREALISTICALLYEARLY 120.0

#define MMS1_REALTIME_SEED 666

#define MMS1_MINETADIV 200.0
#define MMS1_MAXETADIV 20.0

#endif
