#ifndef MMS1_STRUCT_H
#define MMS1_STRUCT_H

#include "minigame/minigame1/meta.h"

#include "meta/mms_filepaths.h"
#include "meta/mms_language.h"

typedef enum
{
	MMS1_OBSTRUCTION_TYPE_CAR0 = 0,
	MMS1_OBSTRUCTION_TYPE_CAR1 = 1,
	MMS1_OBSTRUCTION_TYPE_CAR2 = 2,
	MMS1_OBSTRUCTION_TYPE_CAR3 = 3,
	MMS1_OBSTRUCTION_TYPE_CAR4 = 4,
	MMS1_OBSTRUCTION_TYPE_CAR5 = 5,
	MMS1_OBSTRUCTION_TYPE_CAR6 = 6,
	MMS1_OBSTRUCTION_TYPE_CAR7 = 7,
	MMS1_OBSTRUCTION_TYPE_CAR8 = 8,
	MMS1_OBSTRUCTION_TYPE_CAR9 = 9,
	MMS1_OBSTRUCTION_TYPE_CAR10 = 10,
	MMS1_OBSTRUCTION_TYPE_CAR11 = 11,
	MMS1_OBSTRUCTION_TYPE_CAR12 = 12,
	MMS1_OBSTRUCTION_TYPE_CAR13 = 13,
	MMS1_OBSTRUCTION_TYPE_CAR14 = 14,
	MMS1_OBSTRUCTION_TYPE_CAR15 = 15,
	MMS1_OBSTRUCTION_TYPE_BIKE = 16,
	MMS1_OBSTRUCTION_TYPE_BIKER = 17,
	MMS1_OBSTRUCTION_TYPE_CACTUS = 18,
	MMS1_OBSTRUCTION_TYPE_TUMBLEWEED = 19,
	MMS1_OBSTRUCTION_TYPE_BAG = 20,
	MMS1_OBSTRUCTION_TYPE_BAG2 = 21,
	MMS1_OBSTRUCTION_TYPE_BARREL = 22,
	MMS1_OBSTRUCTION_TYPE_BRICKS = 23,
	MMS1_OBSTRUCTION_TYPE_CRATE = 24,
	MMS1_OBSTRUCTION_TYPE_PIPES = 25
} MMS1_OBSTRUCTION_TYPE;

typedef struct
{
	size_t lane;
	double velocity, leftDrift, rightDrift, driftVelocity, weight, drift, driftAccum, totalVelocity;
	bool deactivate, crashed;
	uint64_t crashedMarker;
	PLEX_RECT space, translatedSpace;
	PLEX_SPRITE* sprite;
} MMS1_OBSTRUCTION;

#endif
